;;	(0 my first car 0)
;;	first-car
;;		gist-question: (2 what 1 you remember 2 first car 3)  
(MAPC 'ATTACHFEAT
'(
  (CAR-BRAND chevrolet ford mustang chevrolet corvair fiat chevette triumph toyota celica simca aronde mini pontiac oldsmobile dodge austin studebaker plymouth mercury cadillac jeep chevy mercedes mercedes-benz volkswagen vauxhall morris garages mg renault willys lincoln packard buick reo stutz franklin jaguar)
  (CGEVRIKER chevy)
  (CAR-BRAND-TWO maxi allegro corvair mustang ranger chevy nova celica corona aronde morris mini festiva stylemaster firebird vista cruiser wagon hawk convertible pickup special coupe deluxe benz beetle custom astra cutlass maverick sedan fleetmaster continental special roadmaster benz roadster bel air THUNDER bird)
  (SHADE dark light mint navy)
  (COLOR black brown blue red silver white green gold champagne purple)
  (FRIEND friends)
  (FAMILY grandchildren grandchild children CHILD DAUGHTER daughters SON sons SPOUSE wife husband siblings brother brothers sister sisters PARENTS MOTHER FATHER mom dad grandparents grandma grandpa GRANDMOTHER GRANDFATHER)
  (GIFT gifts present presents)
))


(READRULES '*first-car-input*
'(
  ; Questions
  1 (0 what 2 you 0 ?)
    2 (What do I remember about my first car ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (What do I remember about my first car ?) (0 :gist)
  1 (0 .WH_ 4 hobbies 0 ?)
    2 (What do I remember about my first car ?) (0 :gist)
  ; Specific answers
  1 (1 .NEG 4 .REMEMBER 0)
    2 ((You do not remember things about your first car \.) (First-car)) (0 :gist)
  1 (0 .CAR-BRAND 1 .CAR-BRAND-TWO 0)
    2 ((The brand of your first car is 2 4 \.) (First-car)) (0 :gist)
  1 (0 .CAR-BRAND-TWO 1 .CAR-BRAND-TWO 0)
    2 ((The brand of your first car is 2 4 \.) (First-car)) (0 :gist)
  1 (0 .CAR-BRAND 0)
    2 ((The brand of your first car is 2 \.) (First-car)) (0 :gist)
  1 (0 .CAR-BRAND-TWO 0)
    2 ((The brand of your first car is 2 \.) (First-car)) (0 :gist)
  1 (0 .SHADE 1 .COLOR 0)
    2 ((The color of your first car is 2 4 \.) (First-car)) (0 :gist)
  1 (0 .COLOR 0)
    2 ((The color of your first car is 2 \.) (First-car)) (0 :gist)
  1 (0 is 2 .GIFT 0)
    2 (0 .GIFT 3 .FAMILY 0)
      3 ((Your first car is a gift from your 4 \.) (First-car)) (0 :gist)
    2 (0 .FAMILY 2 .GIFT 0)
      3 ((Your first car is a gift from your 2 \.) (First-car)) (0 :gist)
    2 (0 .GIFT 0)
      3 ((Your first car is a gift \.) (First-car)) (0 :gist)
  1 (0 mom\'s 0)
    2 ((Your first car was your mom old car \.) (First-car)) (0 :gist)
  1 (0 dad\'s 0)
    2 ((Your first car was your dad old car \.) (First-car)) (0 :gist)
  1 (0 .FAMILY 0)
    2 (0 .FAMILY gives 0)
      3 ((Your first car is a gift from your 2 \.) (First-car)) (0 :gist)
    2 (0 .FAMILY give 0)
      3 ((Your first car is a gift from your 2 \.) (First-car)) (0 :gist)
    2 (0 .FAMILY 0)
      3 ((You used to drive your first car with your 2 \.) (First-car)) (0 :gist)
  1 (0 .FRIEND 0)
    2 ((You used to drive your first car with your 2 \.) (First-car)) (0 :gist)
  1 (0 .COLLEAGUE 0)
    2 ((You used to drive your first car with your 2 \.) (First-car)) (0 :gist)
  1 (0 .NEIGHBOUR 0)
    2 ((You used to drive your first car with your 2 \.) (First-car)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for what you remember about your first car \.) (First-car)) (0 :gist)
))


(READRULES '*reaction-to-first-car-input*
'(
  1 (1 .NEG 1 .REMEMBER 0)
    2 (So it was a long time ago \.) (100 :out)
  1 (0 .CAR-BRAND .CAR-BRAND-TWO 0)
    2 (0 ford 0)
      3 (Cool \! Ford was very popular \. I remember seeing a lot of ford coupes around back then \.) (100 :out)
    2 (0 chevrolet 0)
      3 (Chevy is popular in an international scale \. Nice choice \.) (100 :out)
    2 (0 cadillac 0)
      3 (A cadillac \! Must feel good to drive it in the street \.) (100 :out)
    2 (0 .CAR-BRAND .CAR-BRAND-TWO 0)
      3 (I know some people who drive 2 3 back in my days \. My father lent me a ford though \. A classic choice \.) (100 :out)
  1 (0 .CAR-BRAND-TWO .CAR-BRAND-TWO 0)
    2 (I know some people who drive 2 3 back in my days \. My father lent me a ford though \. A classic choice \.) (100 :out)
  1 (0 .CAR-BRAND 0)
    2 (0 ford 0)
      3 (Yes \, ford was very popular \. I remember seeing a lot of ford coupes around back then \.) (100 :out)
    2 (0 chevrolet 0)
      3 (Chevy is popular in an international scale \. Nice choice \.) (100 :out)
    2 (0 cadillac 0)
      3 (A cadillac \! Must feel good to drive it in the street \.) (100 :out)
    2 (0 .CAR-BRAND 0)
      3 (I know some people who used to drive 2 back in my days \. My father lent me a ford though \. A classic choice \.) (100 :out)
  1 (0 .CAR-BRAND-TWO 0)
    2 (I know some people who used to drive 2 back in my days \. My father lent me a ford though \. A classic choice \.) (100 :out)
  1 (0 .SHADE .COLOR 0)
    2 (0 .SHADE blue 0)
      3 (Blue is my favorite color \! My first car was sea blue \.) (100 :out)
    2 (0 .SHADE .COLOR 0)
      3 (2 3 is a wonderful color \. I would love to have a 3 car \.) (100 :out)
  1 (0 .COLOR 0)
    2 (0 blue 0)
      3 (Blue is a beautiful color \. I also had a blue coupe once \.) (100 :out)
    2 (0 .COLOR 0)
      3 (Interesting to know \. I personally had a blue ford as my graduation gift from my father \.) (100 :out)
  1 (0 .GIFT 0)
    2 (0 .FAMILY 0)
      3 (It sounds lovely to get a car as a gift \. My father gave me a blue chevy after your graduation from college \.) (100 :out)
    2 (0)
      3 (A car\'s a great gift \.) (100 :out)
  1 (0 .FAMILY 0)
    2 (0 mom old car 0)
      3 (It is so generous when parents buy a car for their kid or give them their own car \.) (100 :out)
    2 (I love driving with my husband \. Good old time \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (Your first car can be a very memorable experience \.) (100 :out)
))