;
(READRULES '*feedback-input*
; TBC
'(
  1 (bye)
    2 ((Goodbye \.)) (0 :gist)
  ;; 1 (0 [SEP] 0)
  ;;   2 ((An input was found \: 1 and 3 \.)) (0 :gist)
  ; Top-level nodes match SOPHIE's responses where we previously had opportunity tags
  1 (.WH_ does this mean for my future [SEP] 0)
    ; Second-level nodes detect whether user asked an open-ended question or not
    2 (0 [SEP] 0 .WH_ worries you the .MOST 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    ; If doctor did not ask an open-ended question, gist-clause stores suggestion
    2 ((Question-suggestion \: what worries you the most ?)) (0 :gist)
  1 (what is 1 prognosis [SEP] 0)
    2 (0 [SEP] 0 .DO you .UNDERSTAND your prognosis 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 how .MUCH information .DO you .WANT 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 what scares you about your prognosis 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 how .DO you feel about your prognosis 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 ((Question-suggestion \: do you understand your prognosis ? How much information do you want about your prognosis ? What concerns you the most for your future ?)) (0 :gist)
  1 (.CAN I trust your prognosis [SEP] 0)
    2 (0 [SEP] 0 .DO you .UNDERSTAND your prognosis 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 how .DO you feel about your prognosis 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 ((Question-suggestion \: do you understand your prognosis ? What concerns you the most for your future ?)) (0 :gist)
  1 (what are my options for .TREATMENT [SEP] 0)
    2 (0 [SEP] 0 what scares you about your condition 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 how are you .FEELING about your condition 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 what are your .TREATMENT goals 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 ((Question-suggestion \: what concerns you the most for your future ? What are your treatment goals ?)) (0 :gist)
  ; DEFUNCT -- QUESTIONS BETTER SUITED FOR EMPATHY
  ; 1 (I feel mildly depressed [SEP] 0)
  ;   2 (0 [SEP] 0 What scares you about your condition 0)
  ;    3 ((The doctor asked an open ended question \.)) (0 :gist)
  ;  2 (0 [SEP] 0 How are you feeling about your condition 0)
  ;    3 ((The doctor asked an open ended question \.)) (0 :gist)
  ;  2 (0 [SEP] 0 Were you nervous for this appointment 0)
  ;    3 ((The doctor asked an open ended question \.)) (0 :gist)
  ;   2 ((Question-Suggestion \: What concerns you the most for your future ? What scares you about your condition ? Were you nervous about this meeting ?)) (0 :gist)
  ; 1 (Why have I not been sleeping well [SEP] 0)
  ;  2 (0 [SEP] 0 Were you nervous for this appointment 0)
  ;    3 ((The doctor asked an open ended question \.)) (0 :gist)
  ;  2 (0 [SEP] 0 What happens when you try to sleep 0)
  ;    3 ((The doctor asked an open ended question \.)) (0 :gist)
  ;  2 ((Question-Suggestion \: Were you nervous about this meeting ? Can you elaborate on your sleeping problems ?)) (0 :gist)
  ; 1 (I feel nervous about my future [SEP] 0)
  ;   2 (0 [SEP] 0 What scares you about your condition 0)
  ;    3 ((The doctor asked an open ended question \.)) (0 :gist)
  ;  2 (0 [SEP] 0 How are you feeling about your condition 0)
  ;    3 ((The doctor asked an open ended question \.)) (0 :gist)
  ;  2 (0 [SEP] 0 Were you nervous for this appointment 0)
  ;    3 ((The doctor asked an open ended question \.)) (0 :gist)
  ;  2 ((Question-Suggestion \: What concerns you the most for your future ? What scares you about your condition ? Were you nervous about this meeting ?)) (0 :gist)
  1 (I am sleeping poorly because of my mental health [SEP] 0)
    2 (0 [SEP] 0 what scares you about your condition 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 how are you .FEELING about your condition 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 were you nervous for this .APPOINTMENT 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 ((Question-suggestion \: what concerns you the most for your future ? What scares you about your condition ? Were you nervous about this meeting ?)) (0 :gist)
  ; Tentative - How does chemotherapy work? What should I tell my family? (Can I outlive your prognosis if I have healthy habits?) (Can I outlive your prognosis if I am healthy now?) (Can I outlive your prognosis until the graduation of my grandson?) 
  1 (what are my .TREATMENT options if I .DO not .DO .CHEMOTHERAPY [SEP] 0)
    2 (0 [SEP] 0 what scares you about your condition 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 how are you .FEELING about your condition 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 (0 [SEP] 0 what are your .TREATMENT goals 0)
      3 ((The doctor asked an open ended question \.)) (0 :gist)
    2 ((Question-suggestion \: what concerns you the most for your future ? What are your treatment goals ?)) (0 :gist)
  ; EMPATHY OPPORTUNITIES
  1 (what .SHOULD I .TELL my .FAMILY [SEP] 0)
    2 (0 [SEP] 0 .DO you .WANT me to .BE present when you .TELL your .FAMILY about the prognosis 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 you .SHOULD .REASSURE your .FAMILY about the prognosis 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 you .SHOULD .TELL your .FAMILY the full truth about the prognosis 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 you will .BE .AVAILABLE to .HELP me and my .FAMILY during my cancer .TREATMENT 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 ((Empathy-suggestion \: do you want me to be present when you tell your family about the prognosis ? I\'ll be there for you throughout the whole process \.)) (0 :gist)
  1 (I .KNOW that my cancer has gotten worse \, but i\'m not sure how .BAD it is [SEP] 0)
    2 (0 [SEP] 0 how .DO you feel about your prognosis 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 what scares you about your prognosis 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 how .MUCH .DO you .WANT to .KNOW about your prognosis 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 were you nervous about this meeting 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 ((Empathy-suggestion \: how much do you want to know about your prognosis ? Were you nervous about this meeting ?)) (0 :gist)
  1 (why .HAVE I not been sleeping well [SEP] 0)
    2 (0 [SEP] 0 is your mental health keeping you awake 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 what is on your mind when you .TRY to .SLEEP 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 .CAN you .TELL me about your .PAIN 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 how .DO you rate your .PAIN 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 I am sorry that you are sleeping poorly 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 ((Empathy-suggestion \: what goes through your mind when you try to sleep ? Do you feel pain at night ? I\'m sorry that you\'ve been sleeping poorly \.)) (0 :gist)
  1 (my .PAIN has .RECENTLY been getting worse [SEP] 0)
    2 (0 [SEP] 0 I am sorry that you are in .PAIN 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 .CAN you .TELL me about your .PAIN 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 how .DO you rate your .PAIN 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 .DO you .WANT a stronger .PAIN medication 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 is your .PAIN medication working 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 has the .PAIN become worse 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 .DO you .HAVE the .PAIN .FREQUENTLY 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 ((Empathy-suggestion \: I am sorry that you are in pain \. Can you tell me about your pain ? Has the pain become worse ?)) (0 :gist)
  1 (I feel mildly depressed [SEP] 0)
    2 (0 [SEP] 0 how is your mental health 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 is something harming your mental health 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 what scares you about your condition 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 how are you .FEELING about your condition 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 were you nervous for this .APPOINTMENT 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (Empathy-suggestion \: how have you been recently \? Were you nervous for this appointment ?) (0 :gist)
  1 (I feel anxious about my future [SEP] 0)
    2 (0 [SEP] 0 how is your mental health 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 is something harming your mental health 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 what scares you about your condition 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 how are you .FEELING about your condition 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 were you nervous for this .APPOINTMENT 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 you .SHOULD see a therapist 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 you .SHOULD .TAKE an .ANTIDEPRESSANT 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (Empathy-suggestion \: how is your mental health \? Were you nervous for this appointment ?) (0 :gist)
  1 (why .DO I .HAVE cancer [SEP] 0)
    2 (0 [SEP] 0 I wish that you .DO not .HAVE cancer 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 I am sorry that you .HAVE cancer 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 cancer .CAN affect anyone 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (0 [SEP] 0 cancer .CAN affect the human body suddenly 0)
      3 ((The doctor gave an empathetic response \.)) (0 :gist)
    2 (Empathy-suggestion \: i\'m so sorry that this happened to you \. I wish that there was no such thing as cancer at all \.) (0 :gist)
  ; Empathy Opportunities:
  ; Can I trust my prognosis ?
  ; Can I outlive your prognosis if/until ... ?
  1 (0)
    2 ((NIL Gist \: nothing found for input \.)) (0 :gist)
)) ; END *feedback-input*