;; (what did you have for breakfast ?)
;; (breakfast-today)
;; from-breakfast-today-input
;; (0 I had 4 for breakfast 0) 
;;     gist-question: (2 what 1 you have 2 breakfast 1)
(MAPC 'ATTACHFEAT
'(
  (BREAKFAST-HEALTHY-ONE-WORD FRUIT vegetable vegetables tofu vitamins)
  (FRUIT fruits yogurt clementine clementines apple apples banana bananas grape grapes berries blueberry blueberries strawberry strawberries)
  (BREAKFAST-LIGHT-ONE-WORD cereal bagel bagels oatmeal toast bread almond almonds nut nuts granola muffin muffins cheerios)
  (BREAKFAST-HEAVY-ONE-WORD egg eggs omelette waffle waffles pancake pancakes sausage sausages bacon ham)
  (BREAKFAST-DRINKS-ONE-WORD milk juice coffee tea)
  (BREAKFAST-LIGHT-TWO-WORD bran apple cinnamon blueberry chocolate muffin muffins vitamin pills corn flakes)
  (BREAKFAST-HEAVY-TWO-WORD scrambled egg eggs belgian waffle waffles)
  (BREAKFAST-DRINKS-TWO-WORD FRUIT orange apple juice black coffee herbal green tea)
  (BUTTER-1 peanut almond)
))


(READRULES '*breakfast-today-input*
'(
  ; Reciprocal question
  1 (0 what 2 you 0 ?)
    2 (What did I have for breakfast ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (What did I have for breakfast ?) (0 :gist)
  1 (0 .DO you 2 eat 0 ?)
    2 (What did I have for breakfast ?) (0 :gist)
  1 (0 can you 2 eat 0 ?)
    2 (What did I have for breakfast ?) (0 :gist)
  ; Specific answer
  1 (0 .BREAKFAST-LIGHT-TWO-WORD .BREAKFAST-LIGHT-TWO-WORD 0)
    2 ((You had 2 3 for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 .BREAKFAST-HEAVY-TWO-WORD .BREAKFAST-HEAVY-TWO-WORD 0)
    2 ((You had 2 3 for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 .BREAKFAST-DRINKS-TWO-WORD .BREAKFAST-DRINKS-TWO-WORD 0)
    2 ((You had 2 3 for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 .BREAKFAST-HEALTHY-ONE-WORD 0)
    2 ((You had 2 for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 .BREAKFAST-LIGHT-ONE-WORD 0)
    2 ((You had 2 for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 .BREAKFAST-HEAVY-ONE-WORD 0)
    2 ((You had 2 for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 .BREAKFAST-DRINKS-ONE-WORD 0)
    2 ((You had 2 for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 skipped breakfast 0)
    2 ((You had nothing for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 did not 3 breakfast 0)
    2 ((You had nothing for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 .BUTTER-1 butter 0)
    2 ((You had 2 3 for breakfast \.) NIL) (0 :gist)
  1 (1 nothing 0)
    2 ((You had nothing for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 did not .HAVE 0)
    2 ((You had nothing for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 did not eat 0)
    2 ((You had nothing for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0 had 1 nothing 0)
    2 ((You had nothing for breakfast \.) (Breakfast-today)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for what you had for breakfast \.) (Breakfast-today)) (0 :gist)
))


(READRULES '*reaction-to-breakfast-today-input*
'(
  1 (0 NIL Gist 0)
    2 (That sounds nice \.) (100 :out)
  1 (0 .BREAKFAST-LIGHT-TWO-WORD .BREAKFAST-LIGHT-TWO-WORD 0)
    2 (Sounds like a nice breakfast \. I like 2 3 as well \.) (100 :out)
  1 (0 .BREAKFAST-HEAVY-TWO-WORD .BREAKFAST-HEAVY-TWO-WORD 0)
    2 (I really like 2 3 \, however it is a very heavy breakfast so I can\'t have it often \.) (100 :out)
  1 (0 .BREAKFAST-DRINKS-TWO-WORD .BREAKFAST-DRINKS-TWO-WORD 0)
    2 (0 .BREAKFAST-DRINKS-TWO-WORD tea 0)
      3 (I really like 2 tea \, it\'s very refreshing \.) (100 :out)
    2 (0 .BREAKFAST-DRINKS-TWO-WORD .BREAKFAST-DRINKS-TWO-WORD 0)
      3 (Personally \, I prefer tea to 2 3 \.) (100 :out)
  1 (0 .BREAKFAST-HEALTHY-ONE-WORD 0)
    2 (0 .FRUIT 0)
      3 (I try to have fruit for every breakfast \, it\'s very healthy for me \.) (100 :out)
    2 (I try to have 2 for every breakfast \, it\'s very healthy for me \.) (100 :out)
  1 (0 .BREAKFAST-LIGHT-ONE-WORD 0)
    2 (Sounds like a nice breakfast \. I like 2 as well \.) (100 :out)
  1 (0 .BREAKFAST-HEAVY-ONE-WORD 0)
    2 (I really like 2 \, however it is a very heavy breakfast so I can\'t have it often \.) (100 :out)
  1 (0 .BREAKFAST-DRINKS-ONE-WORD 0)
    2 (0 tea 0)
      3 (I really like tea \, it\'s very refreshing \.) (100 :out)
    2 (0 .BREAKFAST-DRINKS-ONE-WORD 0)
      3 (Personally \, you prefer tea to 2 \.) (100 :out)
  1 (0 .BUTTER-1 butter 0)
    2 (Sounds like a nice breakfast \. I like 2 3 as well \, though it is a little bit too fatty for me \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (You must be hungry \. You should try to eat at least something small for breakfast \.) (100 :out)
))