;;  (what is your favorite food ?)
;;	(favorite-food)
;; 	from-favorite-food-input
;;  (0 food I like 0) (0 do not have a favorite food 0)
;;  	gist-question: (1 what 2 favorite 2 food 1) 
(MAPC 'ATTACHFEAT
'(
  (FOOD-DESCS sweet sour savory salty bitter dry crunchy spicy)
  (FOOD-CATEGORIES vegan vegetarian seafood vegetables FRUIT dessert grain nuts dairy meat)
  (FOOD-ETHNICITY asian chinese mexican japanese italian korean peruvian thai ethiopian indian mediterranean turkish greek cambodian german polish spanish)
  (MORE-COMMON-FOOD-ETHNICITY asian chinese mexican mediterranean greek turkish)
  (FOOD-SEAFOOD fish cod eel herring salmon sardine sardines swordfish tilapia trout tuna caviar crab lobster shrimp oyster clam clams squid octopus calamari sushi)
  (FOOD-VEGETABLES salad celery broccoli garlic cauliflower cucumber spinach leek pumpkin beets kale zucchini cabbage carrot carrots lettuce asparagus potato tomato eggplant pepper quinoa avocado soy pickle pickles corn pea peas mushroom mushrooms onion onions)
  (FOOD-FRUIT apple apples banana bananas orange oranges strawberry strawberries grape grapes pear pears cherry cherries peach peaches lemon lemons mango mangos blueberry blueberries berry berries watermelon watermelons melon melons grapefruit grapefruits pomegranate pomegranates blackberry blackberries apricot apricots cranberry cranberries coconut coconuts tangerine tangerines cantaloupe cantaloupes honeydew honeydews olive olives plantains)
  (FOOD-DESSERT cookie cookies brownies candy pie cheesecake chocolate custard pastry pastries ice cream doughnut donut doughnuts donuts shortcake sundae cake)
  (FOOD-GRAIN pasta spaghetti rice noodles oats oatmeal bread toast cereal bran pancake pancakes waffle waffles)
  (FOOD-NUTS almond almonds walnut walnuts peanut peanuts hazelnut hazelnuts pistachio pistachios cashew cashews pecan pecans chestnut chestnuts)
  (FOOD-DAIRY butter cheese cheddar mozzarella parmesan milk yogurt pudding egg eggs omelette)
  (FOOD-MEAT beef pork chicken lamb duck meatball meatballs sausage steak ribs pepperoni ham salami bacon turkey)
  (FOOD-MISC french fries hot-dog hot-dogs hot dog burger hamburger burgers hamburgers taco tacos stuffing pizza chili sandwich sandwiches sub subs bagel bagels curry soup stew bean beans)
))


(READRULES '*favorite-food-input*
'(
  ; Reciprocal questions
  1 (0 what 2 you 0 ?)
    2 (What is my favorite food ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (What is my favorite food ?) (0 :gist)
  1 (0 your favorite 0 ?)
    2 (What is my favorite food ?) (0 :gist)
  1 (0 .DO you 2 eat 0 ?)
    2 (What is my favorite food ?) (0 :gist)
  1 (0 can you 2 eat 0 ?)
    2 (What is my favorite food ?) (0 :gist)
  ; Specific answer
  1 (0 .FOOD-SEAFOOD 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-VEGETABLES 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-FRUIT .FOOD-DESSERT 0) ;; e.g. "apple pie", "strawberry shortcake"
    2 ((The food you like is 2 3 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-FRUIT 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-DESSERT .FOOD-DESSERT 0) ;; e.g. "ice cream"
    2 ((The food you like is 2 3 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-DESSERT 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-GRAIN 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-NUTS 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-DAIRY 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-MEAT .FOOD-MISC 0) ;; e.g. "turkey sandwich", "pork tacos"
    2 ((The food you like is 2 3 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-MEAT 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-MISC 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-ETHNICITY 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 .FOOD-CATEGORIES 0)
    2 ((The food you like is 2 \.) (Favorite-food)) (0 :gist)
  1 (0 I 1 .NEG 2 .HAVE 3 favorite 0)
    2 (you .DO not .HAVE a favorite food \.)
  1 (0)
    2 ((NIL Gist \: nothing found for the food you like \.) (Favorite-food)) (0 :gist)
))


(READRULES '*reaction-to-favorite-food-input*
'(
  1 (0 .FOOD-SEAFOOD 0)
    2 (I really like 2 ! Seafood is one of my favorite types of food \.) (100 :out)
  1 (0 .FOOD-VEGETABLES 0)
    2 (I like 2 ! It\'s nice since it is both healthy and tastes good \.) (100 :out)
  1 (0 .FOOD-FRUIT .FOOD-DESSERT 0) ;; e.g. "apple pie", "strawberry shortcake"
    2 (I think 2 3 is pretty tasty \. I definitely have a bit of a sweet tooth \.) (100 :out)
  1 (0 .FOOD-FRUIT 0)
    2 (I like 2 ! It\'s nice when food is healthy and tastes good \.) (100 :out)
  1 (0 .FOOD-DESSERT .FOOD-DESSERT 0) ;; e.g. "ice cream"
    2 (I think 2 3 is pretty tasty \. I definitely have a bit of a sweet tooth \.) (100 :out)
  1 (0 .FOOD-DESSERT 0)
    2 (I really like 2 ! I definitely have a bit of a sweet tooth \.) (100 :out)
  1 (0 .FOOD-GRAIN 0)
    2 (I like 2 ! However \, it is a little bit heavy for me \. It\'s very filling \.) (100 :out)
  1 (0 .FOOD-NUTS 0)
    2 (I love 2 ! Crunchy foods are the best \.) (100 :out)
  1 (0 .FOOD-DAIRY 0)
    2 (2 is very tasty \. However \, I cannot have much of it \. It sometime makes my stomach hurt \.) (100 :out)
  1 (0 .FOOD-MEAT .FOOD-MISC 0) ;; e.g. "turkey sandwich", "pork tacos"
    2 (I like 2 3 as well \. However \, I cannot have much of it \. It\'s very filling \.) (100 :out)
  1 (0 .FOOD-MEAT 0)
    2 (I like 2 ! However \, I cannot have much of it \. It\'s very filling \.) (100 :out)
  1 (0 .FOOD-MISC 0)
    2 (Nice \! I like 2 as well \. It\'s very tasty \.) (100 :out)
  1 (0 .FOOD-ETHNICITY 0)
    2 (0 italian 0)
      3 (My daugher loves italian food \. So I used to make pizza and pasta a lot when I was younger \.) (100 :out)
    2 (0 .FOOD-ETHNICITY 0)
      3 (I love 2 food ! It\'s good that there are a lot of 2 restaurants in rochester \.) (100 :out)
    2 (I haven\'t tried 2 food yet \. I will have to taste it some time \.) (100 :out)
  1 (0 .FOOD-CATEGORIES 0)
    2 (0 vegan 0)
      3 (I also like to eat 2 food every now and then \.) (100 :out)
    2 (0 vegetarian 0)
      3 (I also like to eat 2 food \.) (100 :out)
    2 (I try to include 2 in my diet \. It is very beneficial for health \.) (100 :out)
  1 (0 .FOOD-DESCS 0)
    2 (I also like to eat 2 food \.) (100 :out)
  1 (0 not .HAVE a favorite food 0)
    2 (I love eating \! There\'s lots of amazing food out there to taste \!) (100 :out)
  1 (0 NIL Gist 0)
    2 (There\'s lots of amazing food out there to taste \!) (100 :out)
))