; November 25, 2019
;=================================================================
; Word data used in the context of the blocksworld dialogue.
; Factored out so as to avoid duplication in the various rule files.
;
(MAPC 'ATTACHFEAT
'(
  (CORP adidas burger_king esso heineken hp mcdonalds mercedes nvidia pepsi shell sri sri_international starbucks texaco target toyota twitter)
  (BLOCK blocks)
  (TABLE tables)
  (STACK stacks)
  (ROW rows)
  (EDGE edges)
  (FACE faces)
  (PLANE planes)
  (LINE lines)
  (CIRCLE circles)
  (PILE piles)
  (OBJECT objects)
  (COLOR colors)
  (STRUCTURE structures)
  (DIRECTION DIRECTIONS)
  (WAY ways)
  (OTHER others)
  (ONE ones)
  (THING things)
  (CHAIR chairs)
  (BOOK books)
  (BOOKSHELF bookshelves)
  (BOOK_SHELF book_shelves)
  (BED beds)
  (TV tvs)
  (COFFEE_TABLE coffee_tables)
  (POSTER posters)
  (LAPTOP laptops)
  (PEN pens)
  (TREE trees)
  (MICROWAVE microwaves)
  (STOVE stoves)
  (FRIDGE fridges)
  (SOFA sofas)
  (HUMAN humans)
  (CAT cats)
  (WINDOW windows)
  (BOX boxes)
  (PINETREE pinetrees)
  (PINE_TREE pine_trees)
  (PINE pines)
  (BIRD birds)
  (CURTAIN curtains)
  (ANALOG analogs)
  (CLOCK clocks)
  (ANALOG_CLOCK analog_clocks)
  (PIE pies)
  (DOOR doors)
  (HAMMER hammers)
  (TOOTHBRUSH toothbrushes)
  (TOOTH teeth)
  (BRUSH brushes)
  (TOOTH_BRUSH tooth_brushes)
  (BIN bins)
  (RECYCLE_BIN recycle_bins)
  (DESK desks)
  (CEILING ceilings)
  (FAN fans)
  (LIGHT lights)
  (CEILING_FAN ceiling_fans)
  (CEILING_LIGHT ceiling_lights)
  (BANANA bananas)
  (ROSE roses)
  (VASE vases)
  (PENCIL pencils)
  (CARDBOX cardboxes)
  (CARD cards)
  (BOX boxes)
  (CARD_BOX card_boxes)
  (LAMP lamps)
  (PAINTING paintings)
  (PICTURE pictures)
  (APPLE apples)
  (BOWL bowls)
  (PLATE plates)
  (FOOTREST footrests)
  (FOOT feet)
  (FOOT_REST foot_rests)
  (HOLDER holders)
  (PENCIL_HOLDER pencil_holders)
  (AQUARIUM aquariums)
  (UMBRELLA umbrellas)
  (FLOOR floors)
  (FLOOR_LAMP floor_lamps)
  (ROCKING_CHAIR rocking_chairs)
  (TURN turns)
  (TIME times)
  (STAGE stages)
  (STEP steps)
  (QUESTION questions)
  (UTTERANCE utterances)
  (ITERATION iterations)
  (MOVE moves)
  (ACTION actions)
  (PERIOD periods)
  (START starts)
  (BEGINNING beginnings)
  (WHILE whiles)
  (SECOND seconds)
  (MINUTE minutes)
  (HOUR hours)
  (UNDER underneath supporting SUPPORT)
  (CLOSE next)
  (TOUCHING face-to-face abutting against flush)
  (FARTHEST furthest)
  (ROTATED angled swivelled turned)
  (TOUCH touches touched)
  (SUPPORT supports supported)
  (CONNECT connects connected)
  (CONSIST_OF consists_of consisted_of)
  (SIT sits sat)
  (ADJOIN adjoins adjoined)
  (FLANK flanks flanked)
  (FACE faces faced)
  (MOVE moves moved)
  (PUT puts)
  (CHANGE changes changed)
  (PICK_UP picks_up picked_up)
  (ROTATE rotates ROTATED)
  (PLACE places placed)
  (REASON reasons reasoning justification justifications explanation explanations)
  (ADV-EXPLAIN why how)
  (VERB-REL-PAST touched supported connected consisted_of sat adjoined flanked faced moved puts changed picked_up ROTATED placed)
  (PREP-BW on on_to UNDER in behind near TOUCHING facing abutting between from below beneath above next_to close_to near_to visible on_top_of to_the_left_of to_the_right_of in_front_of adjacent_to flush_with towards)
  (PREP-WHERE-ADV relative_to with_respect_to)
  (REL-ADJ near CLOSE TOUCHING facing adjacent flush central)
  (QUAL-ADJ purple blue green yellow orange red pink gray grey black white brown clear visible nearby)
  (NUM-ADJ TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN ELEVEN TWELVE many)
  (SUP-ADJ leftmost rightmost furthest FARTHEST nearest closest highest tallest nearest topmost top uppermost smallest lowest largest centermost shortest backmost longest fewest frontmost)
  (SUP-ADJ-BASE left right far near CLOSE high tall near small low large center central short back long few front)
  (ORD-ADJ first SECOND third fourth fifth sixth seventh eighth ninth tenth eleventh twelfth thirteenth fourteenth fifteenth sixteenth seventeens eighteenth nineteenth twentieth)
  (DIFF-ADJ OTHER different same distinct separate unique)
  (COMPARE-ADJ further closer nearer higher lower taller shorter larger smaller longer wider narrower)
  (ADJ-OBJ QUAL-ADJ REL-ADJ NUM-ADJ SUP-ADJ SUP-ADJ-BASE ORD-ADJ DIFF-ADJ)
  (MOD-N ADJ-OBJ CORP)
  (NOUN-BW BLOCK TABLE STACK ROW EDGE FACE PLANE LINE CIRCLE PILE OBJECT COLOR STRUCTURE left center right back front DIRECTION WAY OTHER ONE THING)
  (NOUN-ROOM TABLE CHAIR BOOK BOOKSHELF BOOK_SHELF BED TV coffee COFFEE_TABLE POSTER LAPTOP PEN TREE MICROWAVE STOVE FRIDGE SOFA HUMAN CAT WINDOW BOX scissors PINETREE PINE_TREE PINE BIRD curtains ANALOG CLOCK ANALOG_CLOCK PIE DOOR HAMMER TOOTHBRUSH TOOTH BRUSH TOOTH_BRUSH recycle BIN RECYCLE_BIN DESK CEILING FAN LIGHT CEILING_FAN CEILING_LIGHT BANANA ROSE VASE PENCIL CARDBOX CARD BOX CARD_BOX LAMP PAINTING PICTURE APPLE BOWL PLATE FOOTREST FOOT rest FOOT_REST HOLDER PENCIL_HOLDER AQUARIUM UMBRELLA FLOOR FLOOR_LAMP ROCKING_CHAIR)
  (NOUN-OBJ NOUN-BW NOUN-ROOM)
  (NOUN-TOTAL total all)
  (VERB BE VERB-REL)
  (BE is are was were)
  (VERB-REL TOUCH SUPPORT CONNECT CONSIST_OF SIT ADJOIN FLANK FACE MOVE PUT CHANGE PICK_UP ROTATE PLACE)
  (VERB-ANSWER ANSWER answered say said tell told mention mentioned claim claimed reply replied respond responded think thought BELIEVE believed know knew)
  (VERB-EXPLAIN explain justify elaborate)
  (NOUN-EXPLAIN ANSWER answers response responses reply replies)
  (AUX-BW DO MODAL)
  (WH-EXPLANATION why how)
  (ADV-E-NUMBER first SECOND third fourth fifth sixth seventh eighth ninth tenth)
  (ADV-E previously before originally initially currently now recently ever since last finally ADV-E-NUMBER)
  (ADV-F-NUMBER once twice thrice)
  (ADV-F always never ADV-F-NUMBER)
  (ADV-HISTORY ADV-F ADV-E)
  (NOUN-HISTORY TURN TIME STAGE STEP QUESTION ANSWER UTTERANCE ITERATION MOVE ACTION PERIOD START BEGINNING WHILE past now SECOND MINUTE HOUR MOMENT present future)
  (PREP-HISTORY at in on PREP-HISTORY-SIMPLE)
  (PREP-HISTORY-SIMPLE during within before after when where WHILE prior_to following preceding since from until)
  (PREP-HISTORY-ADJ ago before previously after later)
  (ADJ-HISTORY-MODIFIER-NUMBER ONE TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN TWENTY THIRTY FORTY FIFTY SIXTY SEVENTY EIGHTY NINETY hundred)
  (ADJ-HISTORY-MODIFIER few couple ADJ-HISTORY-MODIFIER-NUMBER)
  (ADJ-HISTORY-NUMBER first SECOND third fourth fifth sixth seventh eighth ninth tenth)
  (ADJ-HISTORY previous next current initial original following preceding future last final recent ADJ-HISTORY-NUMBER ADJ-HISTORY-MODIFIER)
  (ADV-HIST-MODIFIER just right directly most)
  (ADV-HIST-NUMBER ONE TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN)
  (ADV-HIST-WORD ADV-HISTORY PREP-HISTORY ADJ-HISTORY ADV-HIST-MODIFIER ADV-HIST-NUMBER)
  (ADV_ ADV ADV-HISTORY ADV-HIST-MODIFIER)
  (PREP PREP-BW PREP-HISTORY PREP-WHERE-ADV)
  (ADJ ADJ-OBJ ADJ-HISTORY)
  (NOUN NOUN-OBJ NOUN-HISTORY NOUN-TOTAL)
  (NP-BW NP_ NOUN-BW CORP)
  (NP-ROOM NP_ NOUN-ROOM)
  (NP-OBJ NP-BW NP-ROOM)
))