FROM ubuntu:latest AS basepackages

# Needed to install tzdata
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install OS-level dependencies
RUN apt-get update
RUN apt-get install -y sbcl curl libpq-dev git-all

# Install quicklisp and some dependencies (regardless of the asd) for
# faster builds.
FROM basepackages AS quicklisp
RUN curl 'https://beta.quicklisp.org/quicklisp.lisp' > quicklisp.lisp
RUN sbcl --non-interactive \
    --load "/quicklisp.lisp" \
    --eval "(quicklisp-quickstart:install)" \
    --eval "(ql:quickload '(ironclad cffi alexandria))"

# Install local quicklisp dependencies
RUN git clone https://github.com/genelkim/ttt.git root/quicklisp/local-projects/ttt

# # Install the missing dependencies from the asd file
# FROM quicklisp AS dependencies
# COPY --from=quicklisp /root/ /root/
# RUN mkdir /eta
# WORKDIR /eta
# COPY eta.asd compile-dependencies.lisp ./

# RUN sbcl --disable-debugger --load '/root/quicklisp/setup.lisp' \
# 	 --load 'compile-dependencies.lisp'

# FROM basepackages AS eta
# COPY --from=dependencies /root/ /root/
# RUN mkdir /eta
# WORKDIR /eta
# COPY --from=dependencies /eta/dependencies.core dependencies.core
# COPY . .
# RUN sbcl --core 'dependencies.core'

# ENTRYPOINT [ "./lispapp" ]