(MAPC 'ATTACHFEAT
'(
  ; Synonymous
  (MEET meeting)
  (CARE TREATMENT treatments)
  (COME came)
  (PAIN hurt hurting)
  (MEDICINE medicines medication medications drug DRUGS pill pills med meds DOSE)
  (DRIVE drove driving)
  (APPOINTMENT meeting consultation session)
  (MENTION say)
  (TELL told say INFORM informed notify notified talk TALKING convey conveying)
  (CHEMOTHERAPY chemo chemotherapies)
  (KNOW aware UNDERSTAND)
  (BRING brings)
  (SYMPTOM symptoms)
  (LOSE lost losing)
  (MUCH lot many)
  (CONGRATULATIONS congrats congratulate commend)
  (DIE died dead pass passed depart perish)
  (EFFECT effects)
  (INFECTION infections)
  (UNDER underneath)
  (LEAD leading)
  (HAVE having)
  (DIFFICULT hard impossible)
  (TROUBLE troubles problem problems issue issues hard difficulty)
  (CONCENTRATE concentrating focus focusing)
  (RECOMMEND recommending recommended)
  (ADVISE advising advises advised)
  (SUGGEST suggests suggesting suggested)
  (GIVE gives given giving)
  (PRESCRIBE prescribes prescribed prescribed)
  (ELABORATE continue describe expand)
  (CAN could)
  (MIGHT CAN)
  (MAYBE possible plausible conceivable PERHAPS conceivably possibly)
  (SCALE rate rating)
  (PART parts section sections area areas)
  (TAKE taking)
  (REDNESS red)
  (RESPOND responded react reacted)
  (MADE make makes)
  (OKAY alright well GOOD fine)
  (WAKE waking)
  (DAY daytime)
  (HAPPEN happens)
  (THOUGHT think consider considered look looked)
  (SLEEP sleeping)
  (TRIGGER triggers triggered triggering)
  (PROVOKE provokes provoking provoked)
  (CAUSE causing causes caused TRIGGER PROVOKE)
  (RECENTLY recent lately)
  (CHANCE chances)
  (LOW small minimal)
  (RECOVER recovery survive survival fine)
  (CURE cured curable RECOVER recovery solution fix miracle)
  (ALONE yourself)
  (LONG longer)
  (DOSE doses dosage dosages)
  (TRY trying attempt attempting)
  (BAD horrible terrible awful negative)
  (FRIGHTENING scary worrisome upsetting distressing troubling concerning daunting alarming disturbing)
  (FRIGHTENED afraid worried upset anxious scared nervous apprehensive distressed troubled uneasy concerned)
  (FRIGHTENS scares worries upsets distresses troubles concerns alarms bothers)
  (FRIGHTEN scare worry upset distress TROUBLE concern alarm BOTHER)
  (FEAR-PL fears worries anxieties misgivings doubts)
  (FEAR-SING fear worry anxiety misgiving DOUBT)
  (FEAR-WORDS FEAR-PL FEAR-SING)
  (GUESS guessing)
  (DEPEND depends conditional)
  (LESS lower LOW decrease decreased)
  (IMPROVE improving)
  (MAKE-BETTER better HELP IMPROVE boost)
  (ODDS CHANCE prospects likelihood probability possibility potential)
  (WONDERING ASKING unsure)
  (OPTION options)
  (GROW growing)
  (CONVERSATION discussion)
  (SOUND seem)
  (COFFEE caffeine)
  (ANYTHING something)
  (LIKE same similar identical comparable)
  (NOW present today)
  (HOPEFUL-WORDS hope hopeful confident optimistic BELIEVE upbeat)
  (HAPPY-WORDS happy pleased delighted glad)
  (POSITIVE-WORDS HOPEFUL-WORDS HAPPY-WORDS GOOD)
  (SPEND spending devote devoting)
  (HONEST truthful forthcoming forthright frank open candid direct straight straightforward upfront)
  (AVAILABLE present there around attendence)
  (REASSURE comfort soothe)
  (FACT facts truth)
  (EVERYTHING all full whole entire)
  ; ASR errors
  (TALKING talkin)
  (ASKING askin)
  (YA yes)
  (DATING taking)
  ; General
  (CANCER-ILLNESS cancer disease condition illness)
  (POSADV-AFFIRM certainly course absolutely sure definitely)
  (AFFIRM POS POSADV)
  (ANYONE-HERE-WITH-YOU here with ALONE by)
  (KNOW-GEN KNOW sure aware UNDERSTAND)
  (THINK-GEN think thinking thoughts THOUGHT feel feelings FEELING BELIEVE find)
  (UNDERSTAND-GEN KNOW-GEN THINK-GEN follow following comprehend comprehending)
  (OPINION-GEN opinions THOUGHT thoughts value values need needs preference preferences)
  (FREQUENTLY frequent often MUCH)
  (SLEEP bed bedtime WAKE waking awake insomnia night nighttime)
  (FAMILY parents siblings sibling grandparents)
  (PARENT parents MOTHER FATHER mom dad)
  (CHILD children grandchild grandson grandchildren SON DAUGHTER)
  (MARRIED marry marriage SPOUSE partner husband wife)
  (BEFORE prior LEAD)
  (FEELING feel doing)
  (WORK works working HELP helping treat treating effective)
  (WANT-GEN WANT wanting need needs needing desire desiring)
  (MORE-INFO learn hear TELL say more additional ELABORATE)
  (PREDICT TELL say KNOW)
  (NUMBER ONE NUMBER-PLUR)
  (NUMBER-PLUR TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN ELEVEN TWELVE THIRTEEN FOURTEEN FIFTEEN)
  (NUMBER-VAGUE FEW some many several couple)
  (ELAPSED-TIME-PLUR years months time)
  (ELAPSED-TIME year month ELAPSED-TIME-PLUR)
  (BODY-PART lung lungs bone bones chest back shoulder shoulders)
  (APPRECIATE LIKE LOVE ENJOY)
  (AVATAR-ITEMS shirt sweater pants clothes clothing style glasses hat hair haircut furniture voice)
  (TAG-QUESTION right correct)
  (QUESTION questions)
  (QUESTION-WORD QUESTION inquiry inquiries query queries concerns concern)
  (ASK-GEN ask ASKING talk TALKING)
  (INCORRECT wrong mistaken)
  (UNUSUAL rare infrequent atypical unlikely impossible special odd abnormal peculiar irregular)
  (USUAL likely common probable typical normal regular usually commonly typically normally regularly)
  (SELDOM rarely never infrequently)
  (EXCEPTION anamoly outlier oddity deviation abnormality peculiarity irregularity)
  (LEFT remaining)
  ; Medical history
  (QUIT quitting stop stopping stopped forgo forgoing)
  (SMOKE smokes smoking smoked cigarettes cigarette tobacco)
  (SMOKE-WORDS QUIT SMOKE)
  (DRINK drinking drank wine alcohol beer drunk inebriated)
  (TAKEN-DRUG taken TAKE used use SMOKE)
  (HISTORY background PAST experience)
  (MEDICAL-HISTORY HISTORY DRINK SMOKE RECREATIONAL FAMILY)
  (EXPERIENCED experiencing having had HAVE suffered suffering diagnosed)
  (RECREATIONAL DRUGS marijuana weed)
  ; Side effects
  (SIDE-EFFECT-ADDICTION addiction addicted high dependent withdrawal crave craving cravings)
  (SIDE-EFFECT-FATIGUE fatigue fatigued exhaustion exhausted sleepiness sleepy SLEEP tiredness TIRED drowsy insomnia)
  (SIDE-EFFECT-APPETITE appetite eating eat hunger hungry)
  (SIDE-EFFECT-NAUSEA nausea vomiting vomit sick SICKNESS)
  (SIDE-EFFECT-NEUROPATHY neuropathy numb numbness tingle tingling)
  (SIDE-EFFECTS-INSIGNIFICANT SIDE-EFFECT-FATIGUE SIDE-EFFECT-APPETITE)
  (SIDE-EFFECTS-MODERATE SIDE-EFFECT-NAUSEA diarrhea)
  (SIDE-EFFECTS-SIGNIFICANT hair SIDE-EFFECT-NEUROPATHY SIDE-EFFECT-ADDICTION blood INFECTION)
  ; Treatment goals
  (CANCER-FIGHT FIGHT fighting battle battling treat treating CURE curing)
  (CANCER-LIVE live living survive surviving CURE curing remission)
  (CANCER-GOALS goal goals objective objectives priority priorities preference preferences value values valuing)
  (TREATMENT-OPTION OPTION options possibility possibilities treatments TREATMENT)
  ; Chemotherapy
  (CHEMOTHERAPY-INJECTION injection injections vein veins needle needles)
  (CHEMOTHERAPY-IV iv tube tubes)
  (MEDIPORT infusaport port)
  (CHEMOTHERAPY-CONSULT consult consulting ask ASKING discuss discussing talk TALKING)
  ; Diagnosis details
  (SYMPTOM-WEIGHT weight skinny skinnier heavy heavier fat)
  (SYMPTOM-APPETITE appetite eating)
  (DIAGNOSIS-SYMPTOM SYMPTOM symptoms weight skinny skinnier appetite eating constipation constipated)
  (DIAGNOSIS-NON-SYMPTOM headache headaches chill chills fever fevers nausea eyesight eyes)
  (DIAGNOSIS-TESTS diagnosis test tests result results study studies scan scans)
  (DIAGNOSIS-MORE more another further additional)
  ; Mental health
  (MENT-HEALTH mental depression depressed anxiety anxious worry worried worrying anxiousness unease uneasy schizophrenia)
  (ENERGY mood CONCENTRATE MENT-HEALTH MED-MENT-HEALTH health illness)
  (ANTIDEPRESSANT ssri prozac fluoxetine sertraline zoloft celexa citalopram lexapro escitalopram paroxetine paxil pexeva)
  (THERAPY therapist counseling counselor)
  (MENT-TREATMENT ANTIDEPRESSANT THERAPY)
  ; Medicine
  (MEDICINE-GEN MEDICINE MEDICINE-PARTICULAR)
  (MEDICINE-PARTICULAR PAIN-MED PAIN-MED-OTHER BLOOD-PRESSURE-MED MED-NARCOTIC)
  (MEDICINE-TAKING MEDICINE PAIN-MED)
  (MEDICINE-NOT-TAKING PAIN-MED-OTHER MED-NARCOTIC)
  (PAIN-MED lortab vicodin norco)
  (PAIN-MED-OTHER ibuprofen aleve)
  (MED-NARCOTIC narcotic narcotics oxycodone morphine)
  (MED-CHEMOTHERAPY carboplatin gemcitabine denosumab zometa)
  (MED-MENT-HEALTH ANTIDEPRESSANT ssri prozac fluoxetine sertraline zoloft celexa citalopram lexapro escitalopram paroxetine paxil pexeva)
  (BLOOD-PRESSURE-MED cozar)
  (SLEEP-MEDICATION ambien nyquil lunesta)
  (MED-GIVE RECOMMEND ADVISE SUGGEST GIVE PRESCRIBE)
  (MED-TAKE TAKE taking get getting use using on prescribed)
  (MED-PAST took taken used gotten prescribed)
  (MED-TIME every time times hour hours minute minutes DAY days week weeks)
  (MED-TIME-GEN while period MED-TIME)
  (MED-BETTER better stronger effective heavier)
  (MED-FOR for WORK)
  (MED-HELP CARE HELP helping HELPFUL better effective WORK working benefit)
  (MED-NOTICE notice TELL detect feel observe)
  (MED-WAIT wait GIVE TRY use)
  (MED-INCREASE maximize maximizing increase increasing upping)
  (MED-DOSAGE MUCH many milligrams grams)
  ; Pain
  (PAIN-BAD BAD MUCH strongly intensely badly)
  (PAIN-RETURN COME back return)
  (PAINFUL unpleasant distressing)
  (PAIN unpleasantness suffering agony affliction discomfort hurt)
  (MAKE-WORSE worse worsen harm hurt)
  (PAIN-ALLEVIATE manage control alleviate reduce ease relieve lessen diminish allay assuage palliate moderate mollify IMPROVE relieving improving lessening palliating alleviating controlling managing)
  ; Radiation
  (RADIATION-HELP HELP better alleviate reduce comfort comfortable decrease decreasing)
  ; Comfort care
  (COMFORT-CARE-WORD comfort PALLIATIVE hospice CARE palliation)
  (PALLIATIVE comfort)
  ; Prognosis
  (SPREAD spreading metastasized metastatic)
  (CANCER-INCREASE increase SPREAD GROW grown)
  (PROG-FUTURE will going)
  (GOOD positive fine)
  (PREDICTOR indicator sign signal indication pointer hint)
  (SECOND other another different)
  (IDEA THOUGHT)
  (BENEFICIAL HELPFUL useful worth great GOOD best worthwhile better)
  (SHOULD must ought)
  ; Prognosis Understanding
  (TREATMENT treatments DRUGS drug THERAPY therapies trials trial studies study)
  (EXPERIMENTAL clinical new)
  (HEALTHY health fit shape condition strong GOOD)
  (NOW today SECOND moment present)
  (PAST HISTORY last former previous previously former)
  (UNCLE fred relative people patients he him)
  (PROGNOSIS-MORE LONG more further)
  ; Prognosis Bargaining
  (PERSON-PL people patients cases)
  (MOST majority all preponderance)
  (FEW little couple)
  (GRAD-WORDS grandson graduation graduate)
  ; Sleep
  (SLEEP-PROB problem insomnia)
  (SLEEP-THOUGHT THOUGHT thoughts head mind brain)
  (SLEEP-AWAKE awake up)
  ; Telling family
  (FAMILY-PRON FAMILY they them)
  (LOVE CARE APPRECIATE)
  (GENTLE kind considerate understanding supportive)
))