(MAPC 'ATTACHFEAT
'(
  (GARBAGE plate plates tahou tahou\'s tahoe tahoe\'s)
  (PARK parks highland gvp valley woods letchworth)
  (WATERWAYS genessee lake river ontario irondequoit)
  (ART-GALLERY memorial art gallery)
  (ROCHESTER-RESTAURANT nick tahoe\'s tahou\'s GARBAGE plate dinosaur BARBECUE aladdin\'s chipotle pane vino tapas pita lounge tavern vine lento luck gate max owl golden port dim sum galleria rocco laluna he\'s salena\'s tournedos tornadoes tony d\'s edibles espada espada hot rosita\'s rocky\'s pellegrino\'s scotland yard char christopher\'s veneto john\'s tex-mex matthew\'s east end magnolia\'s bacco\'s hogan\'s hideaway roncone\'s panzari\'s jines nays el savor de la isla el taino chen\'s garden monte alban elmwood inn sinbad\'s stromboli\'s greens legends dogtown sticky lips distillery tropics stock exchange spiro\'s villa bill gray\'s trata el latino mitch\'s mitches village phillips phillip\'s philip\'s chophouse bazil basil delmonico\'s taste ethiopia mex wang\'s fiamma fong ristorante lucano papa joe\'s bee peppa pot havana cuba keenan\'s rizzi\'s grinnell\'s latino antonetta\'s king foo choice remington\'s rick\'s prime rib eros nikko lao charlie brown\'s meda zeppa osteria trinities yangtze romeo\'s henry b\'s cafe cibon carmine\'s red front peppermill nathaniel\'s win sal\'s birdland ridge pomodoro olympia valicia\'s diner hose mcginnity\'s mr \. dominic\'s shui pelican\'s nest cj\'s southern soul campi\'s campies jim\'s mcdonald\'s king hut wendy\'s chipotle pit danforth douglass douglas mel panda express tim horton\'s dibella\'s cam\'s bunga burger saha india grappaf pura vida blimpie starbucks subway brooks landing boulder holley\'s holly\'s hollies steve t\'s jay\'s)
  (SEE-MUSIC music concert)
  (BARBECUE bbq)
  (WATERFALL falls fall)
  (SHOPPING mall outlet)
  (MUSEUM museums)
  (DANCE dancing)
  (MOVIES theater) ; show shows
))


(READRULES '*tour-of-rochester-input*
'(
  ; Reciprocal questions
  1 (0 you 0 .WANT to see 0 ?)
    2 (What would I want to see ?) (0 :gist)
  1 (0 what 0 you 0 .LIKE 0 ?)
    2 (What would I want to see ?) (0 :gist)
  ; Specific answers
  1 (0 .MUSEUM 1 play 0)
    2 ((You would take me to the museum of play \.) (Rochester-tour)) (0 :gist)
  1 (0 eastman house 0)
    2 ((You would take me to george eastman house \.) (Rochester-tour)) (0 :gist)
  1 (0 eastman school 0)
    2 ((You would take me to the eastman school \.) (Rochester-tour)) (0 :gist)
  1 (0 .ART-GALLERY 0)
    2 ((You would take me to an art gallery \.) (Rochester-tour)) (0 :gist)
  1 (0 .PARK 0)
    2 ((You would take me to a park \.) (Rochester-tour)) (0 :gist)
  1 (0 .WATERFALL 0)
    2 ((You would take me to a waterfall \.) (Rochester-tour)) (0 :gist)
  1 (0 .SHOPPING 0)
    2 ((You would take me to shopping \.) (Rochester-tour)) (0 :gist)
  1 (0 ice skating 0)
    2 ((You would take me to ice skating \.) (Rochester-tour)) (0 :gist)
  1 (0 cemetery 0)
    2 ((You would take me to cemetery \.) (Rochester-tour)) (0 :gist)
  1 (0 .SEE-MUSIC 0)
    2 ((You would take me to see music \.) (Rochester-tour)) (0 :gist)
  1 (0 .MUSEUM 0)
    2 ((You would take me to see a museum \.) (Rochester-tour)) (0 :gist)
  1 (0 .DANCE 0)
    2 ((You would take me to dance \.) (Rochester-tour)) (0 :gist)
  1 (0 .MOVIES 0)
    2 ((You would take me to movies \.) (Rochester-tour)) (0 :gist)
  1 (0 .ROCHESTER-RESTAURANT .ROCHESTER-RESTAURANT-T 0)
    2 ((You would take me to 2 3 \.) (Rochester-tour)) (0 :gist)
  1 (0 .ROCHESTER-RESTAURANT 0)
    2 ((You would take me to 2 \.) (Rochester-tour)) (0 :gist)
  ; Unbidden answers
  1 (0 dinosaur 0)
    2 ((You have been to dinosaur barbecue \.) (Dinosaur)) (0 :gist)
  1 (0 .GARBAGE 0)
    2 ((You like garbage plate \.) (Garbage-plate)) (0 :gist)
  1 (0 .ROCHESTER-RESTAURANT 0)
    2 ((Your favorite place to eat is 2 \.) (Rochester-eateries)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for where you would take me \.) (Rochester-tour)) (0 :gist)
))


(READRULES '*thematic-tour-of-rochester-input*
'(
  1 (0 .WATERWAYS 0)
    2 ((You would take me to the water \.) (Rochester-tour)) (0 :gist)
  1 (0 .RESTAURANT-TYPE 0)
    2 ((You would take me to a restaurant \.) (Rochester-tour)) (0 :gist)
))


(READRULES '*reaction-to-tour-of-rochester-input*
'(
  1 (0 .ROCHESTER-RESTAURANT 0)
    2 (That sounds delicious !) (100 :out)
  1 (0 eastman school 0)
    2 (Oh \, cool \. I have heard a lot about eastman school \!) (100 :out)
  1 (0 eastman house 0)
    2 (Oh \, cool \. I love to see the museum and learn more about the kodak founder \!) (100 :out)
  1 (0 art gallery 0)
    2 (Oh \, you have an artistic taste \!) (100 :out)
  1 (0 .PARK 0)
    2 (Oh \, I love nature \!) (100 :out)
  1 (0 water 0)
    2 (Oh \, I love nature \!) (100 :out)
  1 (0 .WATERFALL 0)
    2 (Oh \, I would love to see the waterfall \!) (100 :out)
  1 (0 ice skating 0)
    2 (Oh \, I love ice skating \! That would be fun \!) (100 :out)
  1 (0 see music 0)
    2 (Oh \, I love music \, that would be great \.) (100 :out)
  1 (0 .MUSEUM 0)
    2 (That\'s a great idea \. I love museums \.) (100 :out)
  1 (0 .DANCE 0)
    2 (Oh \, I love dancing \, that would be great \.) (100 :out)
  1 (0 .MOVIES 0)
    2 (I would like that \. I used to go to theater a lot when I was younger \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (That sounds like a nice way to spend the day \.) (100 :out)
)) ; end of *reaction-to-tour-of-rochester-input*