;; (where are you from ?)
;;	(hometown)
;;		from-hometown-input
;;			(0 I am from 0)
;;			gist-question:(3 where are you from 0)
(MAPC 'ATTACHFEAT
'(
  (CITIES NORTHERN-CITIES NORTH-WESTERN-CITIES SOUTHERN-CITIES SOUTH-WESTERN-CITIES EASTERN-CITIES SOUTH-TO-ROCHESTER CENTRAL-CITIES)
  (NORTHERN-CITIES chicago indianapolis columbus detroit cleveland)
  (NORTH-WESTERN-CITIES seattle portland)
  (SOUTH-WESTERN-CITIES phoenix albuquerque)
  (SOUTHERN-CITIES houston dallas austin miami antonio orleans)
  (SOUTH-TO-ROCHESTER atlanta charlotte)
  (WESTERN-CITIES la francisco)
  (EASTERN-CITIES boston nyc philadelphia washington baltimore manhathan brooklyn)
  (CENTRAL-CITIES memphis denver)
  (STATES SOUTHERN-STATES EASTERN-STATES WESTERN-STATES CENTRAL-STATES NORTHERN-STATES OTHER-STATES)
  (SOUTHERN-STATES florida texas arizona georgia)
  (EASTERN-STATES pennsylvania)
  (WESTERN-STATES california oregon washington)
  (CENTRAL-STATES virginia carolina maryland kansas)
  (NORTHERN-STATES ohio michigan vermont massachusetts minnesota illinois)
  (OTHER-STATES alabama alaska arkansas colorado conneticut delaware hawaii idaho indiana iowa kentacky louisiana maine mississippi missouri montana nebraska nevada oklahoma tennessee utah wisconsin wyoming)
  (ROCHESTER-TOWNS fairport irondequoit brighton chili gates henrietta perinton penfield pittsford webster geneva greece)
  (STATES-TWO-WORDS-1 new south north rhode west)
  (STATES-TWO-WORDS-2 york jersey hampshire mexico carolina dakota island virginia)
))


(READRULES '*hometown-input*
'(
  ; Reciprocal questions
  1 (0 what 2 you 0 ?)
    2 (Where am I from ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (Where am I from ?) (0 :gist)
  1 (0 where 2 you from 0 ?)
    2 (Where am I from ?) (0 :gist)
  1 (0 where 2 you grow 0 ?)
    2 (Where am I from ?) (0 :gist)
  ; Specific answer   
  1 (0 new york city 0)
    2 ((You are from 2 3 4 \.) (Hometown)) (0 :gist)
  1 (0 los angeles 0)
    2 ((You are from 2 3 \.) (Hometown)) (0 :gist)
  1 (0 san antonio 0)
    2 ((You are from 2 3 \.) (Hometown)) (0 :gist)
  1 (0 san jose 0)
    2 ((You are from 2 3 \.) (Hometown)) (0 :gist)
  1 (0 san diego 0)
    2 ((You are from 2 3 \.) (Hometown)) (0 :gist)
  1 (0 I am 2 from rochester 0)
    2 ((You are from rochester \.) (Hometown)) (0 :gist)
  1 (0 I am 2 rochesterian 0)
    2 ((You are from rochester \.) (Hometown)) (0 :gist)
  1 (0 I grew up in rochester 0)
    2 ((You are from rochester \.) (Hometown)) (0 :gist)
  1 (0 local 0)
    2 ((You are from rochester \.) (Hometown)) (0 :gist)
  1 (rochester 0)
    2 ((You are from rochester \.) (Hometown)) (0 :gist)
  1 (0 .STATES-TWO-WORDS-1 .STATES-TWO-WORDS-2 0)
    2 ((You are from 2 3 \.) (Hometown)) (0 :gist)
  1 (0 .ROCHESTER-TOWNS 0)
    2 ((You are from 2 \.) (Hometown)) (0 :gist)
  1 (0 .CITIES 0)
    2 ((You are from 2 \.) (Hometown)) (0 :gist)
  1 (0 .STATES 0)
    2 ((You are from 2 \.) (Hometown)) (0 :gist)
  ; Unbidden answer
  1 (0 I am 2 from rochester 0)
    2 ((You ended up in rochester since it is your hometown \.) (Endup-in-rochester)) (0 :gist)
  1 (0 I am 2 rochesterian 0)
    2 ((You ended up in rochester since it is your hometown \.) (Endup-in-rochester)) (0 :gist)
  1 (0 I grew up in rochester 0)
    2 ((You ended up in rochester since it is your hometown \.) (Endup-in-rochester)) (0 :gist)
  1 (0 local 0)
    2 ((You ended up in rochester since it is your hometown \.) (Endup-in-rochester)) (0 :gist)
  1 (0 .ROCHESTER-TOWNS 0)
    2 ((You ended up in rochester since it is your hometown \.) (Endup-in-rochester)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for where you are from \.) (Hometown)) (0 :gist)
))


(READRULES '*reaction-to-hometown-input*
'(
  1 (0 .STATES 0)
    2 (Oh \, I have been to 2 \. It is a nice state \.) (100 :out)
  1 (0 .CITIES 0)
    2 (2 sounds like a fun place to grow up \.) (100 :out)
  1 (0 new york city 0)
    2 (2 3 4 sounds like a fun place to grow up \.) (100 :out)
  1 (0 los angeles 0)
    2 (2 3 sounds like a fun place to grow up \.) (100 :out)
  1 (0 san antonio 0)
    2 (2 3 sounds like a fun place to grow up \.) (100 :out)
  1 (0 san jose 0)
    2 (2 3 sounds like a fun place to grow up \.) (100 :out)
  1 (0 san diego 0)
    2 (2 3 sounds like a fun place to grow up \.) (100 :out)
  1 (0 .STATES-TWO-WORDS-1 .STATES-TWO-WORDS-2 0)
    2 (0 new york 0)
      3 (Oh \, new york state is my favorite \. A lot of snow in winter and then so green during summer \.) (100 :out)
    2 (Oh \, I have been to 2 3 \. It is a nice state \.) (100 :out)
  1 (0 from rochester 0)
    2 (It is nice to meet a rochester native \.) (100 :out)
  1 (0 .ROCHESTER-TOWNS 0)
    2 (2 sounds like a fun place to grow up \. A lot of snow in winter and then so green during summer \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (It sounds like a nice place to grow up \.) (100 :out)
))