(MAPC 'ATTACHFEAT
'(
  ; Synonymous
  (BUT however)
  (WHATEVER what)
  (NICE good great pleasure)
  (BYE goodbye)
  (GO going gone went)
  (MEET meeting)
  (CARE TREATMENT treatments)
  (CALL refer)
  (ALRIGHT OKAY ok fine)
  (COME came coming)
  (ATTEND COME make)
  (CLOSE closest)
  (PAIN hurt hurting)
  (ANSWER answered answering say)
  (MEDICINE medicines medication medications drug DRUGS pill pills med meds DOSE)
  (DRIVE drove driving)
  (APPOINTMENT meeting consultation session)
  (SOMEONE person FRIEND anyone anybody somebody)
  (MENTION say)
  (TALK talks talked TALKING)
  (SPEAK spoke speaking speaks)
  (SHARE sharing TELL telling confide confiding)
  (TELL told say INFORM informed review reviewed notify notified convey conveying telling saying informing notifying DISCUSS SHARE)
  (CHEMOTHERAPY chemo chemotherapies)
  (KNOW aware UNDERSTAND familiar informed acquainted)
  (BRING brings)
  (SYMPTOM symptoms)
  (LOSE lost losing)
  (MUCH lot lots many)
  (CONGRATULATIONS congrats congratulate commend)
  (DIE died dying dead pass passed depart perish)
  (EFFECT effects)
  (RESPONSE RESPOND responded responds responding responses EFFECT)
  (INFECTION infections)
  (UNDER underneath)
  (LEAD leading)
  (HAVE having has had)
  (DIFFICULT hard impossible tough challenging)
  (TROUBLE troubles problem problems issue issues hard difficulty)
  (CONCENTRATE concentrating focus focusing)
  (RECOMMEND recommending recommended)
  (ADVISE advising advises advised)
  (SUGGEST suggests suggesting suggested)
  (GIVE gives given giving gave)
  (PROVIDE offer GIVE supply)
  (PRESCRIBE prescribes prescribed prescribed)
  (ELABORATE continue describe expand)
  (CAN could)
  (MIGHT CAN may)
  (MAYBE possible plausible conceivable PERHAPS conceivably possibly)
  (SCALE rate rating)
  (PART parts section sections area areas)
  (TAKE taking)
  (REDNESS red)
  (RESPOND responded react reacted)
  (MADE make makes making)
  (CREATE created creating MADE produce produced producing)
  (OKAY ALRIGHT well GOOD fine)
  (WAKE waking)
  (DAY daytime)
  (ALLERGY allergies allergic)
  (HAPPEN happens happened happening occur occurs occurring occurred appear appears appearing appeared)
  (LOOK looking looked)
  (THOUGHT think thinking consider considered considering LOOK)
  (SLEEP sleeping)
  (TRIGGER triggers triggered triggering)
  (PROVOKE provokes provoking provoked)
  (CAUSE causing caused TRIGGER triggered triggering PROVOKE provoked provoking produce produced producing RESULT resulted resulting)
  (REASON reasons CAUSE source origin root)
  (MAKE-CHANGE-WORDS CAUSE CREATE)
  (RECENTLY recent lately)
  (LOW small minimal tiny little)
  (RECOVER recovery survive survival fine)
  (CURE cured curable RECOVER recovery solution fix miracle)
  (ALONE yourself)
  (LONG longer further)
  (DOSE doses dosage dosages)
  (TRY trying attempt attempting)
  (BAD horrible terrible awful negative dreadful unpleasant)
  (FRIGHTENING scary worrisome upsetting distressing troubling concerning daunting alarming disturbing)
  (FRIGHTENED afraid worried upset anxious scared nervous apprehensive distressed troubled uneasy concerned)
  (FRIGHTENS scares worries upsets distresses troubles concerns alarms bothers)
  (FRIGHTEN scare worry upset distress TROUBLE concern ALARM BOTHER)
  (FEAR-PL fears worries anxieties misgivings doubts)
  (FEAR-SING fear worry anxiety misgiving DOUBT)
  (FEAR-WORDS FEAR-PL FEAR-SING)
  (ANXIETY-WORD FRIGHTENING FRIGHTENED FRIGHTENS FEAR-WORDS)
  (GUESS guessing guesses guessed)
  (DEPEND depends conditional)
  (LESS lower LOW decrease decreased)
  (IMPROVE improving)
  (MAKE-BETTER better HELP helped IMPROVE improved boost boosted)
  (WONDERING ASKING unsure)
  (OPTION options)
  (CONVERSATION discussion)
  (SOUND sounds sounded sounding SEEM SEEMS seemed seeming appear appears appeared appearing)
  (COFFEE caffeine)
  (ANYTHING something)
  (LIKE same similar identical comparable as)
  (SEEMS looks)
  (SIMILARITY likeness commonality resemblance correspondance)
  (NOW present today)
  (HOPEFUL-WORDS hope hopeful confident optimistic BELIEVE upbeat)
  (HAPPY-WORDS happy pleased delighted glad)
  (POSITIVE-WORDS HOPEFUL-WORDS HAPPY-WORDS GOOD)
  (SPEND spending devote devoting)
  (HONEST truthful forthcoming forthright frank open candid direct straight straightforward upfront)
  (HONEST-ADV honestly truthfully frankly openly candidly directly)
  (AVAILABLE present there here around attendence)
  (REASSURE comfort soothe)
  (COMFORT comfortable)
  (FACT facts truth)
  (EVERYTHING all full whole entire)
  (SUCCUMB DIE victim)
  (STOP stopped prevent prevented keep kept)
  (CHANGE changed changing changes alter alters altering altered transform transforms transforming transformed effect effects)
  (DIFFERENCE CHANGE increase decrease different)
  (SEEM seemed seeming appear appeared appearing LOOK)
  (IN into)
  (SICK ill unwell)
  (CELL cells tissue tissues)
  (LUNG lungs)
  (BODY organ organs LUNG CELL)
  (COMPLICATED complex convoluted)
  (OBVIOUS clear simple easy evident)
  (STAGE stages)
  (FINAL last terminal)
  (ASSUME presume accept act)
  (BE been is are were)
  (EXPLAIN explained explaining explained clarify clarified clarifies clarifying describe describes described describing)
  (SUMMARIZE EXPLAIN)
  (SUMMARY explanation)
  (DESPITE regardless although though)
  (CONFUSED lost bewildered)
  (DISCUSS discussing TALK TALKING discussed talked)
  (ANTICIPATE anticipated anticipating expect expecting expected LOOK forsee forecast count bank PREDICT predicting predicted)
  (READY interested prepared willing)
  (INTEREST interested interesting interests)
  (CERTAIN definite sure)
  (PROCESS processes processed processing)
  (IMAGINE imagined imagines imagining)
  (STARTLE startled startling startles)
  (SURPRISE surprised surprising surprises)
  (ALARM alarming alarmed alarms)
  (STARTLE-WORDS STARTLE SURPRISE ALARM jarring)
  (RESILIENCE backbone spirit strength strong resilient bravery brave courage courageous)
  (AHOLD hold)
  (HELP helped helping helps assist assists assisting assisted SUPPORT supported supporting supports aid aiding aided aids)
  (THANKFUL grateful)
  (UNFORTUNATELY sadly regrettably)
  ; ASR errors
  (TALKING talkin)
  (ASKING askin)
  (YA yes)
  (DATING taking)
  ; General
  (CANCER-ILLNESS cancer disease condition illness prognosis TUMOR)
  (ANYONE-HERE-WITH-YOU here with ALONE by)
  (KNOW-GEN KNOW knew knowing sure aware UNDERSTAND understood understanding)
  (LEARN-GEN LEARN learned learning discover discovered discovering see saw seeing KNOW-GEN)
  (INFORMATION-GEN information info detail details knowledge depth)
  (THINK-GEN think thinking thoughts THOUGHT feel feelings FEELING BELIEVE find)
  (UNDERSTANDING-GEN following comprehending understanding)
  (UNDERSTAND-GEN KNOW-GEN THINK-GEN follow comprehend UNDERSTANDING-GEN)
  (OPINION-GEN opinions THOUGHT thoughts value values need needs preference preferences)
  (BELIEVE-TELL KNOW-GEN THINK-GEN TELL)
  (FREQUENTLY frequent often MUCH)
  (SOMETIMES occasionally occasion infrequently)
  (SLEEP bed bedtime WAKE waking awake insomnia night nighttime)
  (FAMILY parents siblings sibling grandparents relative)
  (PARENT parents MOTHER FATHER mom dad)
  (GRANDCHILD grandchildren grandson granddaughter grandchild\'s grandson\'s granddaughter\'s)
  (CHILD children GRANDCHILD SON DAUGHTER child\'s son\'s daughter\'s)
  (MARRIED marry marriage SPOUSE partner husband wife)
  (CAREER work job employment)
  (BEFORE prior LEAD)
  (FEELING feel feels felt doing)
  (WORK worked works working HELP helping treat treated treating effective successful efficacious HELPFUL)
  (WANT-GEN WANT wanting need needs needing desire desiring hope hoping hoped LIKE)
  (PLAN-GEN THOUGHT plan planned planning intend intended intending aim aiming aimed WANT-GEN)
  (LEARN learned learning learns)
  (HEAR heard hearing hears)
  (MORE-INFO LEARN HEAR TELL told say said more additional further another ELABORATE)
  (PREDICT TELL say KNOW)
  (NUMBER-TOTAL ONE NUMBER-PLUR)
  (NUMBER-PLUR TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN ELEVEN TWELVE THIRTEEN FOURTEEN FIFTEEN)
  (NUMBER-VAGUE FEW some many several couple)
  (ELAPSED-TIME-PLUR years months)
  (ELAPSED-TIME year month ELAPSED-TIME-PLUR)
  (TIME-WORDS time ELAPSED-TIME)
  (TIME-ENOUGH MUCH enough long)
  (BODY-PART LUNG lungs bone bones chest back shoulder shoulders)
  (APPRECIATE LIKE LOVE ENJOY)
  (AVATAR-ITEMS shirt sweater pants clothes clothing style glasses hat hair haircut furniture voice)
  (TAG-QUESTION right correct accurate)
  (ACCURATE right correct)
  (QUESTION questions)
  (QUESTION-WORD QUESTION inquiry inquiries query queries concerns concern)
  (ASK-GEN ask ASKING TALK TALKING)
  (INCORRECT wrong mistaken)
  (UNUSUAL rare infrequent atypical unlikely impossible special odd abnormal peculiar irregular)
  (USUAL likely common probable typical NORMAL regular usually commonly typically normally regularly)
  (SELDOM rarely never infrequently)
  (EXCEPTION anamoly outlier oddity deviation abnormality peculiarity irregularity)
  (OUTLIVE outliving live survive surviving)
  (LEFT remaining)
  (BECOME becomes became becoming get gets getting got gotten)
  (MOVE moved moving GO gone)
  (GROW grows growing grown grew)
  (SHRINK shrinking shrank shrunk decrease)
  (SPECIFIC precise exact detailed)
  (PREDICTION predictions GUESS conjecture conjectures projection projections)
  (ALLOW let permit)
  (IMPORTANT valuable precious dear)
  (NORMAL natural understandable expected)
  (EMOTION emotions reaction reactions FEELING)
  (CONTACT CALL notify phone SPEAK TALK)
  (EXPERTISE expert doctor professional experienced experience)
  (LUCKY luck fortune fortunate blessed)
  (FUTURE-POSS MIGHT will would)
  (YOUR-REF your the)
  ; Medical history
  (QUIT quitting STOP stopping stopped forgo forgoing)
  (SMOKE smokes smoking smoked cigarettes cigarette tobacco)
  (SMOKE-WORDS QUIT SMOKE)
  (DRINK drinking drank wine alcohol beer drunk inebriated)
  (NON-ALCOHOLIC water coffee milk tea soda pop)
  (TAKEN-DRUG taken TAKE used use SMOKE)
  (HISTORY background PAST experience)
  (MEDICAL-HISTORY HISTORY DRINK SMOKE RECREATIONAL FAMILY)
  (EXPERIENCED experiencing having had HAVE suffered suffering diagnosed)
  ; Side effects
  (SIDE-EFFECT-ADDICTION addiction addicted high dependent withdrawal crave craving cravings)
  (SIDE-EFFECT-FATIGUE fatigue fatigued exhaustion exhausted sleepiness sleepy SLEEP tiredness TIRED drowsy insomnia)
  (SIDE-EFFECT-APPETITE appetite eating eat hunger hungry)
  (SIDE-EFFECT-NAUSEA nausea vomiting vomit SICK SICKNESS)
  (SIDE-EFFECT-NEUROPATHY neuropathy numb numbness tingle tingling)
  (SIDE-EFFECTS-INSIGNIFICANT SIDE-EFFECT-FATIGUE SIDE-EFFECT-APPETITE)
  (SIDE-EFFECTS-MODERATE SIDE-EFFECT-NAUSEA diarrhea)
  (SIDE-EFFECTS-SIGNIFICANT hair SIDE-EFFECT-NEUROPATHY SIDE-EFFECT-ADDICTION blood INFECTION)
  (SIDE-EFFECTS-ALL SIDE-EFFECTS-INSIGNIFICANT SIDE-EFFECTS-MODERATE SIDE-EFFECTS-SIGNIFICANT)
  ; Treatment goals
  (CANCER-FIGHT FIGHT fighting battle battling treat treating CURE curing)
  (CANCER-LIVE live living survive surviving CURE curing remission)
  (CANCER-GOALS goal goals objective objectives priority priorities prioritize preference preferences value values valuing)
  (TREATMENT-OPTION OPTION options possibility possibilities treatments TREATMENT CARE choice choices decision decisions)
  (PROGNOSIS-NOTIFICATION-WORDS see saw seen GIVE shown show present presented supply supplied INFORM informed)
  ; Chemotherapy
  (CHEMOTHERAPY-INJECTION injection injections vein veins needle needles)
  (CHEMOTHERAPY-IV iv tube tubes)
  (MEDIPORT infusaport port)
  (CHEMOTHERAPY-CONSULT consult consulting ask ASKING DISCUSS discussing TALK TALKING)
  ; Diagnosis details
  (SYMPTOM-WEIGHT weight skinny skinnier heavy heavier fat)
  (SYMPTOM-APPETITE appetite eating)
  (DIAGNOSIS-SYMPTOM SYMPTOM symptoms weight skinny skinnier appetite eating constipation constipated)
  (DIAGNOSIS-NON-SYMPTOM headache headaches chill chills fever fevers nausea eyesight eyes)
  (DIAGNOSIS-TESTS diagnosis test tests RESULT results study studies scan scans)
  (DIAGNOSIS-MORE more other another further additional)
  ; Mental health
  (MENT-HEALTH mental depression depressed anxiety anxious worry worried worrying anxiousness unease uneasy schizophrenia down)
  (ENERGY mood CONCENTRATE MENT-HEALTH MED-MENT-HEALTH health illness)
  (ANTIDEPRESSANT ssri prozac fluoxetine sertraline zoloft celexa citalopram lexapro escitalopram paroxetine paxil pexeva)
  (THERAPY therapist counseling counselor)
  (MENT-TREATMENT ANTIDEPRESSANT THERAPY)
  ; Medicine
  (MEDICINE-GEN MEDICINE MEDICINE-PARTICULAR)
  (MEDICINE-PARTICULAR PAIN-MED PAIN-MED-OTHER BLOOD-PRESSURE-MED MED-NARCOTIC)
  (MEDICINE-TAKING MEDICINE PAIN-MED)
  (MEDICINE-NOT-TAKING PAIN-MED-OTHER MED-NARCOTIC)
  (PAIN-MED lortab vicodin norco)
  (PAIN-MED-OTHER ibuprofen aleve)
  (MED-NARCOTIC narcotic narcotics oxycodone morphine)
  (MED-CHEMOTHERAPY carboplatin gemcitabine denosumab zometa)
  (MED-MENT-HEALTH ANTIDEPRESSANT ssri prozac fluoxetine sertraline zoloft celexa citalopram lexapro escitalopram paroxetine paxil pexeva)
  (BLOOD-PRESSURE-MED cozar)
  (SLEEP-MEDICATION ambien nyquil lunesta)
  (MED-GIVE RECOMMEND ADVISE SUGGEST GIVE PRESCRIBE)
  (MED-TAKE TAKE taking get getting use using on prescribed)
  (MED-PAST took taken used gotten prescribed)
  (MED-TIME every time times hour hours minute minutes DAY days week weeks)
  (MED-TIME-GEN while period MED-TIME)
  (MED-BETTER better stronger effective heavier)
  (MED-FOR for WORK)
  (MED-HELP CARE HELP helping HELPFUL better effective WORK working benefit)
  (MED-NOTICE notice TELL detect feel observe)
  (MED-WAIT wait GIVE TRY use)
  (MED-INCREASE maximize maximizing increase increasing upping)
  (MED-DOSAGE MUCH many milligrams grams)
  ; Pain
  (PAIN-BAD BAD MUCH strongly intensely badly)
  (PAIN-RETURN COME back return)
  (PAINFUL unpleasant distressing)
  (PAIN PAINFUL unpleasantness suffering agony affliction discomfort hurt)
  (MAKE-WORSE worse worsen worsening harm hurt)
  (PAIN-ALLEVIATE treat manage control alleviate reduce ease relieve lessen diminish allay assuage palliate moderate mollify IMPROVE relieving improving lessening palliating alleviating controlling managing)
  ; Radiation
  (RADIATION-HELP HELP WORK better alleviate reduce comfort comfortable decrease decreasing)
  (RADIATION-TREATMENT radiation CARE THERAPY therapies TREATMENT treatments)
  ; Comfort care
  (COMFORT-CARE-WORD COMFORT PALLIATIVE hospice palliation)
  (PALLIATIVE comfort)
  (REFERRAL request petition)
  (NURSE nurses nursing)
  (COMPANY companies service services business businesses agency agencies)
  (HOME homes house residence apartment flat)
  (VISIT MEET)
  ; Prognosis
  (SPREAD spreading metastasized metastatic)
  (CANCER-WORSE SPREAD worse worsened worsening)
  (CANCER-INCREASE increase SPREAD spreading GROW grown growing advance advancing advanced progress progressing progressed develop developing developed)
  (PROG-FUTURE will going)
  (GOOD positive fine great)
  (PREDICTOR indicator sign signal indication pointer hint)
  (SECOND other another different)
  (IDEA THOUGHT)
  (BENEFICIAL HELPFUL useful worth great GOOD best worthwhile better)
  (SHOULD must ought)
  (STAGE-FOUR FOUR fourth FINAL)
  (PROGNOSIS-WORD prognosis future forecast prediction projection expectation)
  ; Prognosis Understanding
  (TREATMENT treatments DRUGS drug THERAPY therapies trials trial studies study)
  (EXPERIMENTAL clinical new)
  (HEALTHY health)
  (GOOD-HEALTH HEALTHY fit shape condition strong GOOD)
  (NOW today SECOND moment present)
  (PAST HISTORY last former previous previously former)
  (UNCLE fred relative people patients he him)
  (PROGNOSIS-MORE LONG more further)
  ; Prognosis Bargaining
  (PERSON-PL people patients cases one)
  (MOST majority all preponderance everyone)
  (FEW little couple)
  (GRAD-WORDS grandson graduation graduate)
  (AGE old)
  (GRADE year)
  (SCHOOL-TYPE kindergarten elementary primary middle high college university)
  ; Sleep
  (SLEEP-PROB problem insomnia)
  (SLEEP-THOUGHT THOUGHT thoughts head mind brain)
  (SLEEP-AWAKE awake up)
  ; Telling family
  (FAMILY-PRON FAMILY CHILD GRANDCHILD they them)
  (LOVE CARE APPRECIATE)
  (GENTLE kind considerate understanding supportive)
  (DOCTOR-PRON I we me us)
  (BRACE braced bracing)
  (WORST inevitable)
  (POSITION place shoes)
  (PERSPECTIVE view viewpoint outlook point)
  ; Reason for Cancer
  (RESULT consequence EFFECT repercussion ramification culmination aftermath product EFFECT affect)
  (BECAUSE since)
  (DESTROY destroys destroyed destroying wreck wrecks wrecked wrecking ruin ruins ruining ruined)
  (DAMAGE damages damaging damaged)
  (IMPAIR impairs impaired impairing damage damages damaging damaged)
  (DEBILITATE debilitating debilitated debilitates harm harms harming harmed hurt hurts hurting weaken weakens weakened weakening)
  (HURT-WORDS DESTROY IMPAIR DEBILITATE)
  (TUMOR mass cyst malignancy carcinoma growth neoplasm)
  (SUDDEN suddenly unexpected unexpectedly rapid rapidly abrupt abruptly quickly QUICK)
  (LIFE living world lifestyle situation)
))