;;	(Do you use facebook or skype ?)
;;	(use-facebook)
;;		from-use-facebook-input
;;			(0 I do not use social-networks 0) (0 I use social-networks 0)
;;			gist-question: (3 do you 1 facebook 0)
(MAPC 'ATTACHFEAT
'(
  (YES yeah)
  (SOCIAL-NETWORKS facebook SKYPE facetime)
  (SOCIAL-NETWORKS-RELEVANT account profile page skyping OTHER-COMMUNICATION)
  (OTHER-COMMUNICATION EMAIL mail mailing TEXT PHONE)
  (SKYPE skyping skyped)
  (EMAIL emailing)
  (TEXT texting)
  (PHONE call telephone)
  (USE used)
))


(READRULES '*use-facebook-input*
'(
  ; Reciprocal questions
  1 (0 what 2 you 0 ?)
    2 (Do I use facebook or skype ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (Do I use facebook or skype ?) (0 :gist)
  1 (0 .DO you 2 facebook 0 ?)
    2 (Do I use facebook or skype ?) (0 :gist)
  ; Specific answers
  1 (0 I .DO .SOCIAL-NETWORKS 0)
    2 ((You use 4 \.) (Use-facebook)) (0 :gist)
  1 (0 I also 1 .SOCIAL-NETWORKS 0)
    2 ((You use 5 \.) (Use-facebook)) (0 :gist)
  1 (2 .YES 3 .SOCIAL-NETWORKS 0)
    2 ((You use 4 \.) (Use-facebook)) (0 :gist)
  1 (1 definitely 0)
    2 ((You use social-networks \.) (Use-facebook)) (0 :gist)
  1 (3 .NEG 1 .USE 0)
    2 ((You do not use social-networks \.) (Use-facebook)) (0 :gist)
  1 (1 not really 0)
    2 ((You do not use social-networks \.) (Use-facebook)) (0 :gist)
  1 (0 .NEG 3 fan of 0)
    2 ((You do not use social-networks \.) (Use-facebook)) (0 :gist)
  1 (1 I .DO not 1 .SOCIAL-NETWORKS 0)
    2 ((You do not use 6 \.) (Use-facebook)) (0 :gist)
  1 (0 I .DO 1 .SOCIAL-NETWORKS 0)
    2 ((You use 5 \.) (Use-facebook)) (0 :gist)
  1 (0 I .DO .HAVE 1 .SOCIAL-NETWORKS 0) ;; here : I do have a facebook account
    2 ((You use 6 \.) (Use-facebook)) (0 :gist)
  1 (0 I .SOCIAL-NETWORKS 0) ;; here: I skype quite a bit with the three year old
    2 ((You use 3 \.) (Use-facebook)) (0 :gist)
  1 (0 I .HAVE 1 .SOCIAL-NETWORKS 0)
    2 ((You use 5 \.) (Use-facebook)) (0 :gist)
  1 (0 I .USE 2 .SOCIAL-NETWORKS 0)
    2 ((You use 5 \.) (Use-facebook)) (0 :gist)
  1 (0 I am on 1 .SOCIAL-NETWORKS 0)
    2 ((You use 6 \.) (Use-facebook)) (0 :gist)
  1 (1 I 1 .HAVE 1 .SOCIAL-NETWORKS-RELEVANT 0)
    2 ((You use social-networks \.) (Use-facebook)) (0 :gist)
  1 (1 I 1 .USE 1 .SOCIAL-NETWORKS-RELEVANT 0)
    2 ((You use social-networks \.) (Use-facebook)) (0 :gist)
  1 (1 I 1 send 1 .SOCIAL-NETWORKS-RELEVANT 0)
    2 ((You use social-networks \.) (Use-facebook)) (0 :gist)
  1 (1 I .SOCIAL-NETWORKS-RELEVANT 0)
    2 ((You use social-networks \.) (Use-facebook)) (0 :gist)
  1 (0 I .DO not 1 post 0)
    2 ((You do not post on facebook \.) (Use-facebook)) (0 :gist)
  1 (I .DO not 0)
    2 ((You do not use social-networks \.) (Use-facebook)) (0 :gist)
  1 (no 0)
    2 ((You do not use social-networks \.) (Use-facebook)) (0 :gist)
  1 (.YES 0)
    2 ((You use social-networks \.) (Use-facebook)) (0 :gist)
  ; Unbidden answers
  1 (0 I .DO 1 .OTHER-COMMUNICATION 0)
    2 ((You use 5 \.) (Use-facebook)) (0 :gist)
  1 (0 I .DO .HAVE 1 .OTHER-COMMUNICATION 0)
    2 ((You use 6 \.) (Use-facebook)) (0 :gist)
  1 (0 I .OTHER-COMMUNICATION 0)
    2 ((You use 3 \.) (Use-facebook)) (0 :gist)
  1 (0 I .HAVE 1 .OTHER-COMMUNICATION 0)
    2 ((You use 5 \.) (Use-facebook)) (0 :gist)
  1 (0 I .USE 2 .OTHER-COMMUNICATION 0)
    2 ((You use 5 \.) (Use-facebook)) (0 :gist)
  1 (0 I .DO not 1 post 0)
    2 ((You do not post on facebook \.) (Use-facebook)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for if you use social-networks \.) (Use-facebook)) (0 :gist)
))


(READRULES '*reaction-to-use-facebook-input*
'(
  1 (0 .NEG 1 .USE .SOCIAL-NETWORKS 0)
    2 (0 facebook 0)
      3 (I never made a facebook account \, none of my friends are on it \.) (100 :out)
    2 (0 .SKYPE 0)
      3 (My daughter set up skype on my phone last year \. It is a great way to communicate \. Now \, I get to see her while I am talking to her \.) (100 :out)
    2 (0 facetime 0)
      3 (I haven\'t used facetime that much \. I prefer to just call people \.) (100 :out)
  1 (0 you .USE .SOCIAL-NETWORKS 0)
    2 (0 facebook 0)
      3 (I don\'t have a facebook account \, but it might be a good idea to make one \, to keep in touch with friends \.) (100 :out)
    2 (0 .SKYPE 0)
      3 (My daughter set up skype on my phone last year \. It is a great way to communicate \. Now \, I get to see her while I am talking to her \.) (100 :out)
    2 (0 facetime 0)
      3 (I haven\'t used facetime that much \. I prefer to just call people \.) (100 :out)
  1 (0 you .USE .SOCIAL-NETWORKS-RELEVANT 0)
    2 (0 .OTHER-COMMUNICATION 0)
      3 (0 .EMAIL 0)
        4 (I used to use my email much more before \. I find it hard to type recently \.) (100 :out)
      3 (0 .TEXT 0)
        4 (Texting is hard for me \. It takes too much \. I prefer just to call people \.) (100 :out)
      3 (0 .PHONE 0)
        4 (I still like to call people although my daughters prefer skype \.) (100 :out)
    2 (0)
      3 (That\'s nice \. I have a facebook account \, it makes it easier to communicate with friends \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (I don\'t have a facebook account \, but it might be a good idea to make one to stay in touch with friends \.) (100 :out)
))