;; 	Tell me about your favorite vacation.
;;	gist: What does your favorite vacation look like?
;;	(0 favorite vacation 0)
;;	favorite-vacation
;;	(2 What 2 favorite vacation 4)
(MAPC 'ATTACHFEAT
'(
  (VACATION trip travel)
  (COUNTRYSIDE mountain lake river sea BEACH rural cabin)
  (FLY FLYING air airplan aircraft rail railway railroad train boat ship cruise driving drive bus car motor)
  (PARK parks yellowstone grand canyon yosemite national STATE adirondacks adirondack shenandoah acadia olympic zion rockey arches great smoky teton glacier)
  (STATE alabama alaska arizona arkansas california colorado connecticut delaware florida georgia hawaii idaho illinois indiana iowa kansas kentucky louisiana maine maryland massachusetts michigan minnesota mississippi missouri montana nebraska nevada new hampshire new jersey new mexico new york north dakota ohio oklahoma oregon pennsylvania philly rhode south carolina south dakota tennessee texas utah vermont virginia washington west virginia wisconsin wyoming)
  (CITY la nyc sf dc sd los angeles san francisco new york CITY washinton dc san diego houston chicago dallas phoenix boston seattle nashville portland las vegas detroit philadelphia miami atlanta rochester pittsburgh montana)
  (COUNTRY usa united states mexico canada germany italy france switzerland austria belgium poland netherland netherlands denmark czechia uk united kingdom bahamas spain)
  (COUNTRY-CITY amsterdam toronto munich berlin frankfurt rome milan paris strasburg vienna amsterdam montreal)
  (THEME PARK disneyland disney world universal studio legoland lego land seaworld sea world hollywood)
  (BEACH myrtle island cancun maui lanai greek south maya bay waikiki copacabana natadola tenerife langkawi sidari whitehaven lanikai santorini bora bali maldives fiji crete gayman anguilla)
  (FAMILY grandchildren GRANDCHILD children CHILD DAUGHTER daughters SON sons SPOUSE wife husband siblings brother brothers sister sisters parents MOTHER FATHER grandparents GRANDMOTHER GRANDFATHER cousin cousins uncle aunt)
  (FRIEND FRIENDS)
))


(READRULES '*favorite-vacation-input*
'(
  ; Questions
  1 (0 how 2 you 1 .HAVE 1 .VACATION 0 ?)
    2 (How can I take a vacation ?) (0 :gist)
  1 (0 how 2 you 1 take 1 .VACATION 0 ?)
    2 (How can I take a vacation ?) (0 :gist)
  1 (0 what 2 you 0 ?)
    2 (What does my favorite vacation look like ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (What does my favorite vacation look like ?) (0 :gist)
  ; Specific answers
  1 (0 .CITY .CITY .CITY 0) ;; e.g. New York City
    2 ((Your favorite vacation is in 2 3 4 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .CITY .CITY 0)
    2 ((Your favorite vacation is in 2 3 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .CITY 0)
    2 ((Your favorite vacation is in 2 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .STATE .STATE 0)
    2 ((Your favorite vacation is in 2 3 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .STATE 0)
    2 ((Your favorite vacation is in 2 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .COUNTRY .COUNTRY 0) ;; e.g. United States
    2 ((Your favorite vacation is in 2 3 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .COUNTRY-CITY 0)
    2 ((Your favorite vacation is in 2 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .COUNTRY 0)
    2 ((Your favorite vacation is in 2 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .THEME .THEME .THEME 0) ;;Disneyland theme park
    2 ((Your favorite vacation is in 2 3 4 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .THEME .THEME 0) ;;Disneyland park
    2 ((Your favorite vacation is in 2 3 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .THEME 0) ;;Disneyland
    2 ((Your favorite vacation is in 2 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .BEACH .BEACH 0) ;;South beach
    2 ((Your favorite vacation is in 2 3 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .BEACH 0) ;;Fiji
    2 ((Your favorite vacation is in 2 3 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .FAMILY 0)
    2 ((Your favorite vacation is with 2 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .FRIEND 0)
    2 ((Your favorite vacation is with 2 \.) (Favorite-vacation)) (0 :gist)
  1 (0 .FLY 0) ;;Great Smoky
    2 ((You 2 to the place in your favorite vacation \.) (Favorite-vacation)) (0 :gist)
  ; NEW GIST CLAUSE
  ;; 1 (0 NEG 3 vacation 0)
  ;;   2 ((You never have vacation before \.) (Favorite-vacation)) (0 :gist)
  ;; 1 (0 NEG 3 remember 0)
  ;;   2((I never have vacation before \.) (favorite-vacation)) (0 :gist)
  ;; 1 (0 NEG 3 like 0)
  ;;   2((I never have vacation before \.) (favorite-vacation)) (0 :gist) 
  ; NEW GIST CLAUSE
  ; (Not sure if this one is necessary though?)
  ;; 1 (1 NEG 3 family 0) 
  ;;   2 ((You never have vacation with 4 \.)  (Favorite-vacation)) (0 :gist)
  ;; 1 (1 NEG 3 friend 0) 
  ;;   2 ((You never have vacation with 4 \.)  (Favorite-vacation)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for what your favorite vacation is \.) (Favorite-vacation)) (0 :gist)
))


(READRULES '*reaction-to-favorite-vacation-input*
'(
  1 (0 never .HAVE .VACATION 0)
    2 (You should try to have a vacation sometime \, it\'s fun to see the world !) (100 :out)
  1 (0 favorite .VACATION is in .CITY .CITY .CITY 0)
    2 (Wow \, sounds you had a memorable time in 6 7 8 \. I also think 6 7 8 is a nice place \.) (100 :out)
  1 (0 favorite .VACATION is in .CITY .CITY 0)
    2 (0 los angeles 0)
      3 (I love los angeles too \. The weather there is great \.) (100 :out)
    2 (0 san francisco 0)
      3 (I had been to san francisco before for a week \. I can still remember the beautiful view of golden gate bridge \.) (100 :out)
    2 (0 las vegas 0)
      3 (Las vegas is a great place for gambling \, shopping and nightlife \. The perfect place to relax and have fun \.) (100 :out)
    2 (0 .CITY .CITY 0)
      3 (Wow \, sounds you had a memorable time in 2 3 \. I hope to have a nice time there in the future \.) (100 :out)
  1 (0 favorite .VACATION is in .CITY 0)
    2 (Wow \, sounds you had a memorable time in 6 \. I haven\'t been there before \. But I believe it must be a nice place \.) (100 :out)
  1 (0 favorite .VACATION is in .STATE .STATE 0)
    2 (I have never been to 6 7 \. But it sounds an interesting place to travel \.) (100 :out)
  1 (0 favorite .VACATION is in .STATE 0)
    2 (0 california 0)
      3 (It makes sense that you love california \. The sunshine is great there and of course it is much warmer than rochester there \.) (100 :out)
    2 (0 philadelphia 0)
      3 (I have taken a trip to 2 \. The food there was great \.) (100 :out)
    2 (0 .STATE 0)
      3 (2 is a great place to travel \. The time you spent there sounds unforgettable \.) (100 :out)
  1 (0 favorite .VACATION is in .COUNTRY .COUNTRY 0)
    2 (I have never been to 6 7 before \. But that trip sounds very interesting \.) (100 :out)
  1 (0 favorite .VACATION is in .COUNTRY-CITY 0)
    2 (I have never been to 6 before \. But our trip sounds very interesting \.) (100 :out)
  1 (0 favorite .VACATION is in .COUNTRY 0)
    2 (0 germany 0)
      3 (The beer of 2 is very famous \. That\'s a great place to travel \.) (100 :out)
    2 (0 france 0)
      3 (French cuisine is great and I am sure you had a very good time there \. It\'s a romantic place \.) (100 :out)
    2 (0 italy 0)
      3 (I love the great artwork in italy \. I hope I can have the chance to travel there \.) (100 :out)
    2 (0 .COUNTRY 0)
      3 (I have never been to 2 \, but it\'s on my wish list now \.) (100 :out)
  1 (0 favorite .VACATION is in .THEME .THEME .THEME 0)
    2 (0 disney 0)
      3 (Disney is a dream place for me \. I love mickey mouse and snow white \.) (100 :out)
    2 (0 .THEME .THEME .THEME 0)
      3 (You must have spent a wonderful time in 2 3 4 \. That\'s awesome \.) (100 :out)
  1 (0 favorite .VACATION is in .THEME .THEME 0)
    2 (0 universal studio 0)
      3 (Universal studio is a fancy place \. I have been there before and had lots of fun there \.) (100 :out)
    2 (0 .THEME .THEME 0)
      3 (You must have spent a wonderful time in 2 3 \. That\'s awesome \.) (100 :out)
  1 (0 favorite .VACATION is in .THEME 0)
    2 (You must have spent a wonderful time in 2 3 \. That\'s awesome \.) (100 :out)
  1 (0 favorite .VACATION is in .BEACH .BEACH 0)
    2 (The view of 6 7 is fascinating \. The sunshine and the warm sand are great \.) (100 :out)
  1 (0 favorite .VACATION is in .BEACH 0)
    2 (The view of 6 is fascinating \. The sunshine and the warm sand are great \.) (100 :out)
  1 (0 never 3 with .FAMILY 0)
    2 (Actually \, traveling with your 5 is great \. Next time I should try that \.) (100 :out)
  1 (0 never 3 with .FRIENDS 0)
    2 (Actually \, traveling with friends is great \. I have always enjoyed going to a trip with my friends \.) (100 :out)
  1 (0 favorite .VACATION 1 with .FAMILY 0)
    2 (It must be a wonderful time to have a trip with your family \.) (100 :out)
  1 (0 favorite .VACATION 1 with frinds 0)
    2 (It must be a wonderful time to have a trip with your friends \.) (100 :out)
  1 (0 .FLY to the place 0)
    2 (It is a good way to go the place by 2 \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (Sounds great !) (100 :out)
))