;;  Have you ever taken lessons in music, dance, theatre, drawing, or another kind of art?
;;	(0 I have not taken lessons in any kind of art 0)
;;	(0 I have taken lessons in 0)
;;	art-lessons
;;	(Have you ever taken lessons in a kind of art ?)
;;	(3 Have you ever taken lessons 5 art 3)
(MAPC 'ATTACHFEAT
'(
  (ART-TYPES ART-TYPES-PAINT ART-TYPES-DRAW ART-TYPES-PHOTOGRAPHY ART-TYPES-CLAY ART-TYPES-DANCE ART-TYPES-THEATRE ART-TYPES-MUSIC)
  (ART-TYPES-PAINT art paint painting paintings PAINTING-TYPES)
  (PAINTING-TYPES watercolor watercoloring oil oils acrylic abstract modern cubism surrealism surrealist impressionism impressionist medieval realistic realism colorful minimalistic minimalism)
  (ART-TYPES-DRAW draw drawing sketch sketching)
  (ART-TYPES-PHOTOGRAPHY photography photos photographs)
  (ART-TYPES-CLAY clay pots pottery sculptures sculpture sculpting ceramics)
  (ART-TYPES-KNITTING knitting sewing crochet stitching)
  (ART-TYPES-DANCE dance dancing DANCE-TYPES)
  (DANCE-TYPES ballet waltz salsa tango quickstep swing tap jive samba belly latin ribbon break)
  (ART-TYPES-THEATRE theatre theater acting cinema cinematography film animation THEATRE-TYPES)
  (THEATRE-TYPES drama comedy tradgedy play musical reenactment romance)
  (ART-TYPES-MUSIC music MUSIC-TYPES-GROUP MUSIC-TYPES-GENRE MUSIC-TYPES-SINGING MUSIC-TYPES-WIND MUSIC-TYPES-STRING MUSIC-TYPES-OTHER)
  (MUSIC-TYPES-GENRE classical rock pop jazz folk blues rap reggae country punk instrumental opera electronic metal soul disco alternative bluegrass)
  (MUSIC-TYPES-GROUP band orchestra ensemble chorus choir)
  (MUSIC-TYPES-SINGING singing vocal voice opera)
  (MUSIC-TYPES-WIND flute clarinet trumpet trombone bass oboe horn saxophone sax recorder)
  (MUSIC-TYPES-STRING guitar violin cello viola bass)
  (MUSIC-TYPES-OTHER piano drum drums percussion)
  ; Offering art lessons at senior living community
  (SYN-LESSONS lesson lessons class classes school)
))


(READRULES '*art-lessons-input*
'(
  ; Questions
  1 (0 what 2 you 0 ?)
    2 (Have I ever taken lessons in a kind of art ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (Have I ever taken lessons in a kind of art ?) (0 :gist)
  1 (0 .HAVE 2 you 0 ?)
    2 (Have I ever taken lessons in a kind of art ?) (0 :gist)
  1 (0 can 1 you 1 .ART-TYPES 0 ?)
    2 (Can I do art ?) (0 :gist)
  1 (0 how .DO you 1 .ART-TYPES 0 ?)
    2 (Can I do art ?) (0 :gist)
  1 (0 .DO you .LIKE 1 .ART-TYPES 0 ?)
    2 (What types of art do I enjoy ?) (0 :gist)
  ; Specific answers
  1 (0 .ART-TYPES-PAINT 0)
    2 ((You have taken lessons in painting \.) (Art-lessons)) (0 :gist)
  1 (0 .ART-TYPES-DRAW 0)
    2 ((You have taken lessons in drawing \.) (Art-lessons)) (0 :gist)
  1 (0 .ART-TYPES-PHOTOGRAPHY 0)
    2 ((You have taken lessons in photography \.) (Art-lessons)) (0 :gist)
  1 (0 .ART-TYPES-CLAY 0)
    2 ((You have taken lessons in clay \.) (Art-lessons)) (0 :gist)
  1 (0 .ART-TYPES-KNITTING 0)
    2 ((You have taken lessons in knitting \.) (Art-lessons)) (0 :gist)
  1 (0 .ART-TYPES-DANCE 0)
    2 ((You have taken lessons in 2 \.) (Art-lessons)) (0 :gist)
  1 (0 .ART-TYPES-THEATRE 0)
    2 ((You have taken lessons in theatre \.) (Art-lessons)) (0 :gist)
  1 (0 .ART-TYPES-MUSIC 0)
    2 ((You have taken lessons in 2 \.) (Art-lessons)) (0 :gist)
  1 (0 .NEG 1 taken 0)
    2 ((You have not taken lessons in any kind of art \.) (Art-lessons)) (0 :gist)
  1 (0 .NEG 1 had 0)
    2 ((You have not taken lessons in any kind of art \.) (Art-lessons)) (0 :gist)
  1 (0 .NEG really 0)
    2 ((You have not taken lessons in any kind of art \.) (Art-lessons)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for areas you have taken lessons in \.) (Art-lessons)) (0 :gist)
))


(READRULES '*reaction-to-art-lessons-input*
'(
  1 (0 taken lessons 1 painting 0)
    2 (I think painting can be beautiful \, but I was never very good at it \. You are lucky you could get experience with it \.) (100 :out)
  1 (0 taken lessons 1 drawing 0)
    2 (Drawing is a fun way to spend your time \! I like drawing as well \, though I am not very good at it \.) (100 :out)
  1 (0 taken lessons 1 photography 0)
    2 (I love taking photos \, especially of nature \. I never had formal training in it though \.) (100 :out)
  1 (0 taken lessons 1 clay 0)
    2 (Clay sculpting sounds interesting \, I don\'t know much about it but I have seen some really neat creations \.) (100 :out)
  1 (0 taken lessons 1 knitting 0)
    2 (Kniting is a good skill to have \. I am sure it can come in handy when I need to fix broken fabric \.) (100 :out)
  1 (0 taken lessons 1 .ART-TYPES-DANCE 0)
    2 (0 ballet 0)
      3 (That\'s cool \! I am not sure how people do ballet \, it seems like it would make me really dizzy \.) (100 :out)
    2 (0 salsa 0)
      3 (Salsa dancing \, very interesting \. I always found it fun to watch on dancing shows \.) (100 :out)
    2 (Dance lessons sound like a lot of fun \, a good way to get excersize too \.) (100 :out)
  1 (0 taken lessons 1 theatre 0)
    2 (Theatre lessons sound interesting \, making movies has always just seemed like magic to me \.) (100 :out)
  1 (0 taken lessons 1 .ART-TYPES-MUSIC 0)
    2 (0 .MUSIC-TYPES-GENRE 0)
      3 (I have heard some 2 music before \, it seems like a really fun genre to play \.) (100 :out)
    2 (0 .MUSIC-TYPES-GROUP 0)
      3 (Playing music with a group is even more fun than playing music by myself \. I played flute in school band when I was younger \.) (100 :out)
    2 (0 .MUSIC-TYPES-SINGING 0)
      3 (That\'s awesome that you sang \! I am sure it must have sounded beautiful \.) (100 :out)
    2 (0 .MUSIC-TYPES-WIND 0)
      3 (Wind instruments are fun to play \. I played the flute when I was younger \.) (100 :out)
    2 (0 .MUSIC-TYPES-STRING 0)
      3 (I always found string instruments really difficult \. They sure sound nice though \!) (100 :out)
    2 (It\'s great that you had some music education growing up \!) (100 :out)
  1 (0 .NEG taken lessons 0)
    2 (Well \, it\'s never too late to start taking more art lessons \!) (100 :out)
  1 (0 NIL Gist 0)
    2 (I think it\'s important to have a way to express yourself through art \.) (100 :out)
))