(READRULES '*reaction-to-question-specific-session*
; This tree can be used to define reactions to questions specific to a particular module/session. Here the rule
; tree is empty, but it can be overridden in day1/rules to add specific rules.
;
'(
)) ; END *reaction-to-question-specific-session*


(READRULES '*reaction-to-question*
; Here we match any important questions which may branch off into a sub-dialogue, i.e. initiate a sub-schema.
; A separate tree is used for matching any less relevant questions, which prompt Eta to give an answer but then
; return to the central track of the conversation.
;
'(
  ; Preempt any reactions specific to a particular module
  1 (0)
    2 *reaction-to-question-specific-session* (0 :subtree)
  ; Questions about pain
  1 (.CAN I .TELL you about my .PAIN ?)
    2 say-pain-worse.v (3 :schema)
    2 say-pain-worse.v (3 :schema)
    2 (I did have some pain during swallowing after radiation as well \, but that\'s improved a bit \.) (0 :out)
  1 (how .DO I rate my .PAIN ?)
    2 say-pain-worse.v (0 :schema)
  1 (where is the .PAIN located ?)
    2 say-pain-worse.v (0 :schema)
  1 (does it hurt to 2 ?)
    2 say-pain-worse.v (0 :schema)
  1 (did my .PAIN .COME back ?)
    2 say-pain-worse.v (0 :schema)
  1 (has the .PAIN .BECOME worse ?)
    2 say-pain-worse.v (0 :schema)
  1 (.DO you .HAVE the .PAIN .FREQUENTLY ?)
    2 say-pain-worse.v (0 :schema)
  1 (.CAN I .TELL you about my .PAIN instead of test results ?)
    2 say-pain-worse.v (100 :schema)
    2 ask-about-test-results.v (0 :schema)
  ; Questions about how you got your diagnosis
  1 (how did I get my diagnosis ?)
    2 explain-how-got-diagnosis.v (0 :schema)
  1 (what symptoms .DO I .HAVE ?)
    2 explain-symptoms.v (0 :schema)
  1 (.HAVE I changed weight ?)
    2 mention-lost-weight.v (0 :schema)
  1 (how .MUCH weight .HAVE I lost ?)
    2 mention-lost-weight.v (0 :schema)
  1 (.HAVE I changed appetite ?)
    2 mention-lost-appetite.v (0 :schema)
  1 (.DO I .HAVE the .SYMPTOM of 2 ?)
    2 deny-symptom.v (0 :schema) ; might need to be made more specific, but we're assuming that this is
  ; a "catch-all" rule for any symptom which isn't captured as another
  ; gist-clause listed above
  1 (what test results am I referring to ?)
    2 ask-about-test-results.v (0 :schema)
  1 (.DO I .KNOW what the tests say ?)
    2 ask-about-test-results.v (0 :schema)
  1 (.CAN I .SUMMARIZE my test results ?)
    2 ask-about-test-results.v (0 :schema)
  1 (how .DO I feel about my test results ?)
    2 ask-about-test-results.v (0 :schema)
  1 (.DO I .HAVE a .QUESTION about my test results ?)
    2 ask-about-test-results.v (0 :schema)
  1 (how .MUCH information .DO I .WANT about my test results ?)
    2 ask-about-test-results.v (0 :schema)
  1 (.DO I .WANT my .FAMILY to .BE present when you .TELL me about the test results ?)
    2 ask-about-test-results.v (0 :schema)
  1 (.DO I .WANT anyone to .BE present when you .TELL me about the test results ?)
    2 ask-about-test-results.v (0 :schema)
  1 (how has my condition gotten worse ?)
    2 say-pain-worse.v (0 :schema)
  ; Questions about radiation treatment
  1 (did I get radiation .TREATMENT ?)
    2 mention-radiation-time.v (0 :schema)
  1 (did I get any hair loss or .REDNESS during radiation .TREATMENT ?)
    2 discuss-radiation-symptoms.v (0 :schema)
  1 (did the .PAIN .RESPOND to radiation .TREATMENT ?)
    2 mention-feeling-better-after-radiation.v (0 :schema)
  ; Questions about appointment
  1 (did I .DRIVE here ?)
    2 explain-drove-today.v (0 :schema)
  1 (is anyone here with me ?)
    2 explain-here-alone.v (0 :schema)
  ; Questions about chemotherapy
  1 (did my doctor .MENTION .CHEMOTHERAPY ?)
    2 ask-if-need-chemotherapy.v (0 :schema)
  1 (what .CHEMOTHERAPY details are you .ASKING about ?)
    2 ask-how-chemotherapy-works.v (0 :schema)
  1 (.DO I .UNDERSTAND how .CHEMOTHERAPY works ?)
    2 ask-how-chemotherapy-works.v (0 :schema)
  1 (.DO I .HAVE a .QUESTION about .CHEMOTHERAPY ?)
    2 ask-about-chemotherapy-side-effects.v (0 :schema)
  1 (what are my feelings about .CHEMOTHERAPY ?)
    2 ask-if-need-chemotherapy.v (0 :schema)
  ; Questions about sleep
  1 (.HAVE I been sleeping .OKAY ?)
    2 explain-not-sleeping-well.v (0 :schema)
  1 (how often am I waking up at night ?)
    2 explain-not-sleeping-well.v (0 :schema)
  1 (.DO I .SLEEP during the .DAY ?)
    2 mention-taking-naps.v (0 :schema)
  1 (what is on my mind when I .TRY to .SLEEP ?)
    2 explain-not-sleeping-well.v (0 :schema)
  1 (what happens when I .TRY to .SLEEP ?)
    2 explain-not-sleeping-well.v (0 :schema)
  1 (what is my .SLEEP routine ?)
    2 discuss-sleep-routine.v (0 :schema)
  1 (is my mental health keeping me awake ?)
    2 explain-not-sleeping-well.v (0 :schema)
  1 (is .COFFEE keeping me awake ?)
    2 explain-not-sleeping-well.v (0 :schema)
  1 (.CAN I .TELL you about my .SLEEP instead of test results ?)
    2 explain-not-sleeping-well.v (100 :schema)
    2 ask-about-test-results.v (0 :schema)
  ; Questions about energy
  1 (how is my .ENERGY ?)
    2 mention-fatigue.v (0 :schema)
  1 (.HAVE I had .TROUBLE concentrating ?)
    2 mention-trouble-concentrating.v (0 :schema)
  1 (how is my mental health ?)
    2 mention-mild-depression.v (0 :schema)
  1 (is something harming my mental health ?)
    2 mention-anxiety.v (0 :schema)
  1 (what parts of my future feel out of my control ?)
    2 explain-why-future-feels-out-of-control.v (0 :schema)
  ; Questions about medicine
  1 (.DO I .HAVE allergies to any .MEDICINE ?)
    2 deny-allergies.v (0 :schema)
  1 (what .MEDICINE am I taking ?)
    2 mention-taking-lortab.v (0 :schema)
  1 (how were you prescribed your current .PAIN medication ?)
    2 mention-taking-lortab.v (0 :schema)
  1 (what dosage of .PAIN medication am I taking ?)
    2 mention-taking-lortab.v (0 :schema)
  1 (am I taking .PAIN-MED ?)
    2 mention-taking-lortab.v (0 :schema)
  1 (how often am I taking medication ?)
    2 mention-lortab-frequency.v (0 :schema)
  1 (does taking medication more .FREQUENTLY .HELP ?)
    2 mention-lortab-frequency.v (0 :schema)
  1 (am I taking .PAIN-MED-OTHER ?)
    2 mention-taking-lortab.v (0 :schema)
  1 (am I taking .BLOOD-PRESSURE-MED ?)
    2 mention-blood-medication.v (0 :schema)
  1 (am I taking .MED-NARCOTIC ?)
    2 mention-taking-lortab.v (0 :schema)
  1 (is the .PAIN medication working at all ?)
    2 ask-why-pain-medication-not-working.v (0 :schema)
  1 (is the .PAIN medication working ?)
    2 ask-why-pain-medication-not-working.v (0 :schema)
  1 (how is the .PAIN medication working ?)
    2 ask-why-pain-medication-not-working.v (0 :schema)
  1 (.DO I .WANT stronger .PAIN medication ?)
    2 ask-about-pain-medication-side-effects.v (0 :schema)
  1 (.DO I need more .MEDICINE ?)
    2 ask-for-lortab-refill.v (0 :schema)
  1 (.DO I .HAVE a .QUESTION about my .MEDICINE ?)
    2 ask-why-pain-medication-not-working.v (0 :schema)
  ; Comfort care
  1 (.HAVE I considered comfort .CARE ?)
    2 ask-how-comfort-care-works.v (0 :schema)
  1 (.DO I .UNDERSTAND how comfort .CARE works ?)
    2 ask-how-comfort-care-works.v (0 :schema)
  1 (.DO I .HAVE a .QUESTION about comfort .CARE ?)
    2 ask-how-comfort-care-works.v (0 :schema)
  ; Questions about medical history
  1 (what is my .HISTORY with alcohol ?)
    2 discuss-drinking-habits.v (100 :schema)
    2 (At one time \, I suppose I used to have a drink or two maybe three or four days a week \. I have cut back since then though \. Now \, since the cancer diagnosis \, I only have a couple drinks a week \.) (0 :out)
  1 (what is my .HISTORY with smoking ?)
    2 discuss-smoking-habits.v (100 :schema)
    2 (I have been a heavy smoker since high school \, but I kicked the habit six months ago \.) (0 :out)
  1 (what is my .HISTORY with .MED-NARCOTIC ?)
    2 mention-taking-lortab.v (0 :schema)
  1 (does my .FAMILY .HAVE a .HISTORY of mental illness ?)
    2 discuss-history-mental-illness.v (100 :schema)
    2 (No \, no one in my family has any history of mental illness \.) (0 :out)
  1 (how did my parents .DIE ?)
    2 discuss-parent-deaths.v (0 :schema)
  ; Questions about talking with family
  1 (.DO my .FAMILY .KNOW about my cancer ?)
    2 ask-what-to-tell-family.v (100 :schema)
    2 (My family knows that I have cancer already \, but not much else \.) (0 :out)
  1 (.DO I .WANT you to .BE present when I .TELL my .FAMILY about the prognosis ?)
    2 ask-what-to-tell-family.v (100 :schema)
    2 (I can\'t tell you how much I appreciate the offer \, but I think I should break the news to them myself \.) (0 :out)
  1 (how .MUCH .DO I .WANT my .FAMILY to .KNOW about the prognosis ?)
    2 ask-what-to-tell-family.v (100 :schema)
    2 (Now that I think about it more \, my son and daughter both should probably know as much as I do about the prognosis \, since I may need their help as the cancer progresses \. My grandson \, though \, he\'s only in middle school \, and i\'d like to protect him for as long as I can \.) (0 :out)
  1 (who .IN my .FAMILY .DO I .WANT to .TELL about the prognosis ?)
    2 ask-what-to-tell-family.v (100 :schema)
    2 (I\'d have to tell my son \, and certainly my daughter \. I\'m currently staying with both her and my grandson here in rochester \, and I imagine i\'ll probably lean on her a lot more as the cancer progresses \.) (0 :out)
  1 (.DO I .WANT you to .CONTACT a .FAMILY member .NOW ?)
    2 ask-what-to-tell-family.v (100 :schema)
    2 (No thank you \. My daughter is at work and my grandson is at school right now \. I\'d prefer not to bother them and I would feel comfortable telling them myself later \.) (0 :out)
  1 (what .CAN you .DO to .HELP me break the news to my .FAMILY ?)
    2 ask-what-to-tell-family.v (0 :schema)
  ; Questions about treatment options
  1 (what .DO I .UNDERSTAND about my .TREATMENT options ?)
    2 ask-about-treatment-options.v (0 :schema)
  1 (.DO I .HAVE a .QUESTION about my .TREATMENT options ?)
    2 ask-about-will-experimental-therapies-help.v (0 :schema)
  1 (what are my .TREATMENT goals ?)
    2 ask-about-treatment-options.v (0 :schema)
    2 ask-how-comfort-care-works.v (0 :schema)
  1 (what is the prognosis that was given to me previously ?)
    2 ask-about-treatment-options.v (0 :schema)
    2 (I was told I probably wouldn\'t have a long time left \, maybe two or three years at best \.) (0 :out)
  1 (am I .READY to start discussing .TREATMENT options ?)
    2 ask-about-prognosis.v (0 :schema)
  1 (how .MUCH information .DO I .WANT about my prognosis ?)
    2 ask-about-prognosis.v (0 :schema)
  ; Questions about prognosis
  ; TODO: should instantiate a schema where SOPHIE explains her (possibly incorrect) knowledge of
  ; her prognosis; e.g., "I know you said two to three months, but I feel pretty good now"
  1 (.DO I .UNDERSTAND my prognosis ?)
    2 ask-about-prognosis.v (0 :schema)
    2 ask-if-can-trust-prognosis.v (0 :schema)
  1 (how .DO I feel about my prognosis ?)
    2 ask-about-prognosis.v (0 :schema)
  1 (what scares me about my prognosis ?)
    2 ask-about-prognosis.v (0 :schema)
  1 (.DO I .HAVE a .QUESTION about my prognosis ?)
    2 ask-about-prognosis.v (0 :schema)
  1 (how .SPECIFIC .DO I .WANT you to .BE about my prognosis ?)
    2 ask-about-prognosis.v (0 :schema)
  1 (am I .READY to .DISCUSS my .TREATMENT goals ?)
    2 ask-about-prognosis.v (0 :schema)
  1 (.DO I .WANT my .FAMILY to .BE present when you .TELL me about the prognosis ?)
    2 ask-about-prognosis.v (0 :schema)
  1 (.DO I .WANT anyone to .BE present when you .TELL me about the prognosis ?)
    2 ask-about-prognosis.v (0 :schema)
  1 (how prepared for the prognosis are my .FAMILY ?)
    2 ask-about-prognosis.v (0 :schema)
    2 (My family do know that my cancer is there and that it hasn\'t gone away \. They told me that no matter how bad it gets \, they\'re going to stick by me no matter what \.) (0 :out)
  1 (what causes me to .BELIEVE that my cancer has gotten worse ?)
    2 say-pain-worse.v (0 :schema)
  ; Questions about reason for cancer
  1 (how .HAVE I been .FEELING since the cancer metastasized ?)
    2 mention-anxiety.v (0 :schema)
  ; Open-ended questions 
  1 (what .DO I .UNDERSTAND ?)
    2 explain-understanding-of-condition.v (0 :schema)
  1 (how am I .FEELING about my condition ?)
    2 explain-understanding-of-condition.v (0 :schema)
  1 (what scares me about my condition ?)
    2 explain-understanding-of-condition.v (0 :schema)
  1 (what is the .MOST .IMPORTANT thing for my future ?)
    2 explain-future-goals.v (0 :schema)
  1 (was I nervous for this .APPOINTMENT ?)
    2 mention-anxiety.v (0 :schema)
  1 (.CAN you .CALL me sophie ?)
    2 confirm-name.v (0 :schema)
  1 (.CAN I .HEAR you ?)
    2 confirm-doctor-is-audible.v (0 :schema)
  1 (what would .HELP me manage my condition ?)
    2 say-how-to-help.v (0 :schema)
  1 (0)
    2 *reaction-to-question-minor* (0 :subtree)
))


(READRULES '*reaction-to-question-minor*
; Here we match any question gist clauses which are considered "minor", i.e. off-topic or otherwise
; not expected to branch off into a further sub-dialogue.
'(
  ; Questions about daughter
  1 (where does my .DAUGHTER .WORK ?)
    2 (She works as a nurse in the county school system \. She\'s very diligent \. They gave her an award last year \, but i\'m blanking on the name of it \.) (0 :out)
  1 (where does my .SON .WORK ?)
    2 (He\'s in construction management \, out over in utica \. He supervised the team that built the new firehouse there last year \.) (0 :out)
  1 (how old is my .DAUGHTER ?)
    2 (She\'s thirty four \. Turning thirty five in a few months \.) (0 :out)
  1 (how old is my .SON ?)
    2 (He\'ll be celebrating his fortieth this year \, and is not happy about it \.) (0 :out)
  1 (.DO I .HAVE any grandchildren ?)
    2 (Yes \, one grandson \. He\'s starting middle school this year and is absolutely thrilled about it \.) (0 :out)
  1 (.DO I .HAVE any children ?)
    2 (Yes \, i\'m staying with my daughter and her husband here in rochester \, but I have a son out in utica as well \.) (0 :out)
  1 (.DO I live .ALONE ?)
    2 (I live with my daughter and her husband while i\'m here in rochester \.) (0 :out)
  1 (am I .MARRIED ?)
    2 (I was for about twenty years \. But as we got older and the kids went off to college \, things just didn\'t work out as well as we thought they would \. We separated about ten years ago and divorced two years later \.) (0 :out)
  1 (.CAN I .TELL you about my .FAMILY ?)
    2 (Yes \, certainly \! Let me see \, I was married for twenty years \, but separated with my ex husband when the kids went off to college \. We\'re still on good terms though \, and I was thinking of catching up with him now that i\'m back in new york \. I also have two children \, a son who lives in utica and a daughter who lives here \, in rochester.she has a son \, my grandson \, who just turned twelve and is starting middle school this year \.) (0 :out)
  1 (how am I doing today ?)
    2 ([SAD] the pain isn\'t too bad today \. I\'m mostly just anxious \.) (0 :out)
; Questions about family (Todo)
))