;;  What is the best part of advances in technology these days? 
;;	(0 the best part of advances in technology is 0)   (0 no good in advances in technology 0)
;;	technology-best-part
;;	(What is the best part of advances in technology ?) 
;;	(3 what 3 best part of advances in technology 3) 
(MAPC 'ATTACHFEAT
'(
  (TRANSPORTATION bus taxi uber lyft bike MAP navigator)
  (SOCIAL facetime facebook messenger massage TEXT call touch CONTACT)
  (NETWORK news event events information)
  (MEDICAL medicine treatment)
  (GAME entertain entertainment music video videos appliction applictions)
  (CAMERA pictures photos photo)
  (CONVENIENT FAST INDEPENDENT assistive assist)
  (SAVE MONEY time)
  (MAP maps)
))


(READRULES '*technology-best-part-input*
'(
  ; Questions
  1 (0 what 3 best part of advances in technology 0 ?)
    2 (What is the best part of advances in technology ?) (0 :gist)
  1 (0 how .DO you think 3 best part of advances in technology 0 ?)
    2 (What is the best part of advances in technology ?) (0 :gist)
  1 (0 what 2 you 0 ?)
    2 (What is the best part of advances in technology ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (What is the best part of advances in technology ?) (0 :gist)
  ; Specific answers
  1 (0 .TRANSPORTATION 0)
    2 ((The best part of advances in technology is 2 \.) (Technology-best-part)) (0 :gist)
  1 (0 .SOCIAL 0)
    2 ((The best part of advances in technology is 2 \.) (Technology-best-part)) (0 :gist)
  1 (0 .NETWORK 0)
    2 ((The best part of advances in technology is 2 \.) (Technology-best-part)) (0 :gist)
  1 (0 .MEDICAL 0)
    2 ((The best part of advances in technology is 2 \.) (Technology-best-part)) (0 :gist)
  1 (0 .GAME 0)
    2 ((The best part of advances in technology is 2 \.) (Technology-best-part)) (0 :gist)
  1 (0 .CAMERA 0)
    2 ((The best part of advances in technology is 2 \.) (Technology-best-part)) (0 :gist)
  1 (0 .CONVENIENT 0)
    2 ((The best part of advances in technology is 2 \.) (Technology-best-part)) (0 :gist)
  1 (0 .SAVE .SAVE 0)
    2 ((The best part of advances in technology is save 3 \.) (Technology-best-part)) (0 :gist)
  1 (0 .MAP 0)
    2 ((The best part of advances in technology is mobile maps \.) (Technology-best-part)) (0 :gist)
  1 (0 .NEG 1 think 0)
    2 ((There is no good in advances in technology \.) (Technology-best-part)) (0 :gist)
  1 (0 .NEG 1 .LIKE 0)
    2 ((There is no good in advances in technology \.) (Technology-best-part)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for what the best part of advances in technology is \.) (Technology-best-part)) (0 :gist)
))


(READRULES '*reaction-to-technology-best-part-input*
'(
  1 (0 .TRANSPORTATION 0)
    2 (Technology definitely makes transporation much easier \. I remember when people had to use paper maps \, now I can just use my smartphone \!) (100 :out)
  1 (0 .SOCIAL 0)
    2 (It\'s great to be able to talk with friends more easily \, even if they\'re currently somewhere far away \.) (100 :out)
  1 (0 .NETWORK 0)
    2 (I think sometimes news can be overwhelming with current technology \. But it definitely is helpful to know of events immediately \.) (100 :out)
  1 (0 .MEDICAL 0)
    2 (People seem to be living longer and healthier lives than ever due to better medical technology \.) (100 :out)
  1 (0 .GAME 0)
    2 (I don\'t spend a lot of time playing video games \, but it\'s a fun activity for many \.) (100 :out)
  1 (0 .CAMERA 0)
    2 (I love looking at pictures from around the world \. This probably wouldn\'t be possible without technology \!) (100 :out)
  1 (0 .CONVENIENT 0)
    2 (I think it\'s great that people can live more convenient and independent lives \.) (100 :out)
  1 (0 .SAVE .SAVE 0)
    2 (The free time people have today due to technology can allow them to use their mind for even better tasks \.) (100 :out)
  1 (0 .MAP 0)
    2 (I love to use the map on my phone \. I never get lost using it \.) (100 :out)
  1 (0 no good 0)
    2 (I understand that \. I think you should try to think of the helpful things that technology does for us too though \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (Technology seems to have done a lot to make our lives easier \. Sometimes it\'s hard to adjust \, but I hope you can find it helpful too \.) (100 :out)
))