;; (what are your hobbies ?)
;;	(hobbies)
;;		from-hobbies-input
;;			(0 my hobby is 0) (0 do not like 2 hobby 0)
;;			gist-question:(3 what are 1 hobbies 0)
(MAPC 'ATTACHFEAT
'(
  (EXERCISE run running zoomba yoga taichi tai chi gym biking bike hike hiking)
  (WALK walking)
  (GARDEN gardening gardener lawn floral plant plants)
  (SEW sewing)
  (KNIT knitting)
  (SEW- SEW KNIT crochet)
  (WATER-RELATED boat boating kayak kayaking canoeing swimming swim swimmer)
  (GAME games cards card scrabble)
  (MOVIES theater) ;show shows
  (MUSIC concert concerts singing)
  (READ reading BOOK)
  (DRAWING painting)
  (BOOK books)
  (SPORT sports volleyball basketball baseball)
  (GOLF golfing)
  (FRIEND FRIENDS)
  (TRAVEL)
  (COOK cooking)
  (VOLUNTEER volunteering)
  (GRANDCHILD grandchildren grandson granddaughter babysitting)
  (ART artist)
  (DANCE dancing)
  (CRAFT crafting crafts craftwork handicraft handiwork)
  (HAVE having)
  (HOBBY hobbies)
))


(READRULES '*hobbies-input*
'(
  ; Reciprocal questions
  1 (0 what 2 you 0 ?)
    2 (What are my hobbies ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (What are my hobbies ?) (0 :gist)
  1 (0 .WH_ 4 hobbies 0 ?)
    2 (What are my hobbies ?) (0 :gist)
  ; Specific answers
  1 (0 .EXERCISE 0)
    2 (0 tai chi 0)
      3 ((Your hobby is tai chi \.) (Hobbies)) (0 :gist)
    2 ((Your hobby is 2 \.) (Hobbies)) (0 :gist)
  1 (0 beach 0)
    2 (0 .WALK 4 beach 0)
      3 ((Your hobby is walking on the beach \.) (Hobbies)) (0 :gist)
    2 ((Your hobby is going to the beach \.) (Hobbies)) (0 :gist)
  1 (0 .GARDEN 0)
    2 ((Your hobby is gardening \.) (Hobbies)) (0 :gist)
  1 (0 .SEW- 0)
    2 ((Your hobby is 2 \.) (Hobbies)) (0 :gist)
  1 (0 .WATER-RELATED 0)
    2 ((Your hobby is a kind of water sport \.) (Hobbies)) (0 :gist)
  1 (0 play .GAME 0)
    2 ((Your hobby is playing 3 \.) (Hobbies)) (0 :gist)
  1 (0 .MOVIES 0)
    2 ((Your hobby is going to movies \.) (Hobbies)) (0 :gist)
  1 (0 .MUSIC 0)
    2 ((Your hobby is 2 \.) (Hobbies)) (0 :gist)
  1 (0 .SPORT 0)
    2 ((Your hobby is sports \.) (Hobbies)) (0 :gist)
  1 (0 .GOLF 0)
    2 ((Your hobby is golf \.) (Hobbies)) (0 :gist)
  1 (0 .READ 0)
    2 ((Your hobby is reading \.) (Hobbies)) (0 :gist)
  1 (0 .BOOK clubs 0)
    2 ((Your hobby is reading \.) (Hobbies)) (0 :gist)
  1 (0 .LIBRARY 0)
    2 ((Your hobby is going to library \.) (Hobbies)) (0 :gist)
  1 (0 .DANCE 0)
    2 ((Your hobby is dance \.) (Hobbies)) (0 :gist)
  1 (0 .CRAFT 0)
    2 ((Your hobby is doing crafts \.) (Hobbies)) (0 :gist)
  1 (0 .FRIEND 0)
    2 ((Your hobby is being with friends \.) (Hobbies)) (0 :gist)
  1 (0 .TRAVEL 0)
    2 ((Your hobby is traveling \.) (Hobbies)) (0 :gist)
  1 (0 .COOK 0)
    2 ((Your hobby is cooking \.) (Hobbies)) (0 :gist)
  1 (0 .VOLUNTEER 0)
    2 ((Your hobby is volunteering \.) (Hobbies)) (0 :gist)
  1 (0 .GRANDCHILD 0)
    2 ((Your hobby is being with your grandchildren \.) (Hobbies)) (0 :gist)
  1 (0 .HAVE 2 over 0)
    2 ((Your hobby is having people over \.) (Hobbies)) (0 :gist)
  1 (0 party 0)
    2 ((Your hobby is having party \.) (Hobbies)) (0 :gist)
  1 (0 .DRAWING 0)
    2 ((Your hobby is 2 \.) (Hobbies)) (0 :gist)
  1 (0 .NEG .LIKE 2 .HOBBY 0)
    2 ((You do not like any hobby \.) (Hobbies)) (0 :gist)
  ; Unbidden answers
  1 (0 .READ 0)
    2 ((You like reading \.) (Like-to-read)) (0 :gist)
  1 (0 .READ 4 .BOOK-GENRE 0)
    2 (0 science .FICTION 0)
      3 ((You like reading science fiction \.) (Like-to-read)) (0 :gist)
    2 ((You like reading 2 \.) (Like-to-read)) (0 :gist)
  1 (0 .BOOK club 0)
    2 ((You like reading in book club \.) (Like-to-read)) (0 :gist)
  1 (0 .LIBRARY 0)
    2 ((You like reading in library \.) (Like-to-read)) (0 :gist)
  1 (0 kindle 0)
    2 ((You like reading on kindle \.) (Like-to-read)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for what your hobby is \.) (Hobbies)) (0 :gist)
))


(READRULES '*reaction-to-hobbies-input*
'(
  1 (0 .EXERCISE 0)
    2 (It\'s good to stay active \.) (100 :out)
  1 (0 beach 0)
    2 (I like going to the beach \, too \.) (100 :out)
  1 (0 gardening 0)
    2 (Gardening is a good hobby \. It\'s nice to be outdoors \.) (100 :out)
  1 (0 .SEW- 0)
    2 (0 .KNIT 0)
      3 (That\'s nice \! Knitting a very practical hobby too \.) (100 :out)
    2 (0 .SEW 0)
      3 (That\'s nice \! Sewing is a very practical hobby too \.) (100 :out)
    2 (0 crochet 0)
      3 (That\'s nice \! Crochet is a very practical hobby too \.) (100 :out)
  1 (0 water .SPORT 0)
    2 (That sounds cool \. I can\'t go in the water for obvious reasons \, but it looks fun \.) (100 :out)
  1 (0 playing .GAME 0)
    2 (3 sounds like a fun game \.) (100 :out)
  1 (0 .MOVIES 0)
    2 (That\'s nice \. I like movies too \.) (100 :out)
  1 (0 .MUSIC 0)
    2 (That\'s great \! I like music too \.) (100 :out)
  1 (0 sports 0)
    2 (That sounds fun \. It\'s good to stay active \.) (100 :out)
  1 (0 .GOLF 0)
    2 (That\'s great \. It\'s nice to spend time on the golf course \.) (100 :out)
  1 (0 reading 0)
    2 (Oh \, that\'s nice \! I like reading too \.) (100 :out)
  1 (0 .LIBRARY 0)
    2 (I like going to the library \, too \. I can always find an interesting book to read \.) (100 :out)
  1 (0 .DANCE 0)
    2 (Dancing is really fun \! It\'s good to stay active \.) (100 :out)
  1 (0 .CRAFT 0)
    2 (Doing crafts is a good way to unwind \. Also you can make things you wish in exactly the shape \, size \, and color you like \. That\'s great \.) (100 :out)
  1 (0 .DRAWING 0)
    2 (That\'s great \. It\'s nice to spend time on artistic activities such as 2 \.) (100 :out)
  1 (0 .FRIEND 0)
    2 (It\'s nice to talk with friends \. It helps you stay positive \.) (100 :out)
  1 (0 traveling 0)
    2 (I like traveling \. It\'s fun to see new places \.) (100 :out)
  1 (0 cooking 0)
    2 (Cooking is really fun \! I like trying out new recipes \.) (100 :out)
  1 (0 volunteering 0)
    2 (Volunteering is nice \. It\'s good to give back to the community \.) (100 :out)
  1 (0 grandchildren 0)
    2 (It\'s nice to be with family \. I have heard grandchildren are especially fun \.) (100 :out)
  1 (0 .ART 0)
    2 (Art is a cool hobby \. It\'s fun to be creative \.) (100 :out)
  1 (0 .HAVE 1 over 0)
    2 (It is cool to have party and hang out with others \.) (100 :out)
  1 (0 party 0)
    2 (It is cool to have party and hang out with others \.) (100 :out)
  1 (0 .DO not .LIKE 2 .HOBBY 0)
    2 (I suggest that you find some fun activities \. It helps you to relieve the stress of everyday life \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (That sounds like a neat way to spend your time \!) (100 :out)
))