;; (do you like to read ?)
;;	(like-to-read)
;;		from-like-to-read-input
;;			(0 I do not like reading 0) (0 I like reading 0)
;;			gist-question:(3 do 1 like to read 0)
(MAPC 'ATTACHFEAT
'(
  (YES yeah)
  (BOOK-GENRE NOVEL novels magazines MAGAZINE health MYSTERY mysteries fictions FICTION non-fictions NON-FICTION romance historical detective humor biographies autobiography ART literature philosophy RELIGION ethics newspaper horror horrors satire diaries cookbooks COOKBOOK poetry)
  (READ reading reader)
))


(READRULES '*like-to-read-input*
'(
  ; Reciprocal question
  1 (0 what 2 you 0 ?)
    2 (Do I like to read ?) (0 :gist)
  1 (0 how 2 you 0 ?)
    2 (Do I like to read ?) (0 :gist)
  1 (0 .DO you 2 .LIKE 2 .READ 0 ?)
    2 (Do I like to read ?) (0 :gist)
  1 (0 .DO you 2 .READ 0 ?)
    2 (Do I read ?) (0 :gist)
  ; Specific input
  1 (0 .BOOK-GENRE 0)
    2 (0 science .FICTION 0)
      3 ((You like reading science fiction \.) (Like-to-read)) (0 :gist)
    2 ((You like reading 2 \.) (Like-to-read)) (0 :gist)
  1 (0 .BOOK club 0)
    2 ((You like reading in book club \.) (Like-to-read)) (0 :gist)
  1 (0 .LIBRARY 0)
    2 ((You like reading in library \.) (Like-to-read)) (0 :gist)
  1 (0 kindle 0)
    2 ((You like reading on kindle \.) (Like-to-read)) (0 :gist)
  1 (0 .HATE 2 .READ 0)
    2 ((You do not like reading \.) (Like-to-read)) (0 :gist)
  1 (0 cannot 2 .READ 0)
    2 ((You do not like reading \.) (Like-to-read)) (0 :gist)
  1 (0 .NEG 4 .READ 0)
    2 ((You do not like reading \.) (Like-to-read)) (0 :gist)
  1 (0 .NEG 3 reader 0)
    2 ((You do not like reading \.) (Like-to-read)) (0 :gist)
  1 (1 I .DO not 0)
    2 ((You do not like reading \.) (Like-to-read)) (0 :gist)
  1 (no 0)
    2 ((You do not like reading \.) (Like-to-read)) (0 :gist)
  1 (2 .YES 0)
    2 ((You like reading \.) (Like-to-read)) (0 :gist)
  1 (0 .LIKE to .READ 0)
    2 ((You like reading \.) (Like-to-read)) (0 :gist)
  1 (0 I 3 reader 0)
    2 ((You like reading \.) (Like-to-read)) (0 :gist)
  1 (0 .LISTEN 3 .BOOK 0)
    2 ((You like reading and listening to audio books \.) (Like-to-read)) (0 :gist)
  ; Unbidden input
  1 (0 .BOOK-GENRE 0)
    2 (0 science .FICTION 0)
      3 ((You like reading science fiction \.) (Things-like-to-read)) (0 :gist)
    2 ((You like reading 2 \.) (Things-like-to-read)) (0 :gist)
  1 (0 .HATE 2 .READ 0)
    2 ((No book type you like to read \.) (Things-like-to-read)) (0 :gist)
  1 (0 cannot 2 .READ 0)
    2 ((No book type you like to read \.) (Things-like-to-read)) (0 :gist)
  1 (0 .NEG 2 .READ 0)
    2 ((No book type you like to read \.) (Things-like-to-read)) (0 :gist)
  1 (1 I .DO not 0)
    2 ((No book type you like to read \.) (Things-like-to-read)) (0 :gist)
  1 (no 0)
    2 ((No book type you like to read \.) (Things-like-to-read)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for whether you like reading \.) (Like-to-read)) (0 :gist)
))


(READRULES '*reaction-to-like-to-read-input*
'(
  1 (0 NIL Gist 0)
    2 (Reading is a lot of fun \. I enjoy spending some time on reading everyday \.) (100 :out)
  1 (0 you .LIKE reading 0)
    2 (0 .BOOK-GENRE 0)
      3 (0 science .FICTION 0)
        4 (I like reading science fiction \. I go check websites and find ones with the highest score \.) (100 :out)
      3 (0 health 0)
        4 (I like reading about 2 \. I go check websites and find ones with the highest score \.) (100 :out)
      3 (0 .ART 0)
        4 (I like reading about 2 \. I go check websites and find ones with the highest score \.) (100 :out)
      3 (0 .RELIGION 0)
        4 (I like reading about 2 \. I go check websites and find ones with the highest score \.) (100 :out)
      3 (0 ethics 0)
        4 (I like reading about 2 \. I go check websites and find ones with the highest score \.) (100 :out)
      3 (I like reading 2 \. I go check websites and find ones with the highest score \.) (100 :out)
    2 (0 .BOOK club 0)
      3 (Being in a book club is fun \! It\'s also a good place to socialize \.) (100 :out)
    2 (0 .LIBRARY 0)
      3 (I like going to the library \. It\'s always fun to find a new book \.) (100 :out)
    2 (0 kindle 0)
      3 (That sounds nice \. I personally like kindle better \, but some people still prefer paper books \.) (100 :out)
    2 (0 audio books 0)
      3 (That\'s nice \. I like listening to audio books in the car \.) (100 :out)
    2 (Reading is a lot of fun \. I enjoy it too \.) (100 :out)
  1 (0 .DO not .LIKE reading 0)
    2 (That\'s fine \, there are plenty of other fun things to do \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (There\'s a lot of good books out there to discover \.) (100 :out)
))