; Transduction tree for inferring additional facts from the gist-clause interpretations of user input
;
; Questions asked by SOPHIE:
; (Will an antidepressant help with my pain ?)
; (What are the side effects of chemotherapy ?)
; (Should I get comfort care ?)
; (How will I know if my pain medication is working ?)
; (Should I try medication before I try therapy ?)
; (Can I get addicted to narcotics ?)
; (What are the side effects of stronger pain medication ?)
; (Why have I not been sleeping well ?)
; (What is my prognosis ?)
; (What do my test results mean ?)
; (What are my options for treatment ?)
; (What are my treatment options if I do not do chemotherapy ?)
; (Do you think chemotherapy will help ?)
; (Do you think radiation will help ?)
; (I would like a refill of medicine \.)
; (Can I have a stronger pain medication ?)
; (How does chemotherapy work ?)
; (How does comfort care work ?)
; (Has the cancer gotten worse ?)
; (Do I need chemotherapy ?)
; (Will stronger pain medication help me sleep ?)
; (What should I tell my family ?)
; (Why isn\'t the pain medication working anymore ?)
; (Are you sure that I do not need comfort care ?)
; (Are you sure the cancer has not gotten worse ?)
;
; 2 (^me know.v (ans-to ')) (0 :ulf)
;
(READRULES '*clause-pragmatics-tree*
'(
  1 (0 my cancer 2 gotten worse 0)
    2 (^me know.v (ans-to '(Has the cancer gotten worse ?))) (0 :ulf)
  1 (0 a side .EFFECT of the medication is 0)
    2 (0 a side .EFFECT of the medication .BE 2 .SIDE-EFFECTS-SIGNIFICANT 2 \. 0)
      3 (^me know.v (ans-to '(Can I have a stronger pain medication ?))) (0 :ulf)
    2 (^me know.v (ans-to '(What are the side effects of stronger pain medication ?))) (0 :ulf)
  1 (0 a side .EFFECT of .CHEMOTHERAPY is 0)
    2 (^me know.v (ans-to '(What are the side effects of chemotherapy ?))) (0 :ulf)
  1 (0 .ONE way to get .CHEMOTHERAPY is 0)
    2 (^me know.v (ans-to '(How does chemotherapy work ?))) (0 :ulf)
  1 (0 I .SHOULD .TAKE an .ANTIDEPRESSANT 0)
    2 (^me know.v (ans-to '(Will an antidepressant help with my pain ?))) (0 :ulf)
  1 (0 I .SHOULD see a therapist 0)
    2 (^me know.v (ans-to '(Should I try medication before I try therapy ?))) (0 :ulf)
  1 (0 I .SHOULD .TAKE a narcotic 0)
    2 (^me know.v (ans-to '(Can I have a stronger pain medication ?))) (0 :ulf)
  1 (0 you 3 think I need radiation 0)
    2 (^me know.v (ans-to '(Do you think radiation will help ?))) (0 :ulf)
  1 (0 you 3 think I 1 need .CHEMOTHERAPY 0)
    ; TODO: this should infer answer to comfort care as well, rather than just chemotherapy
    2 (0 you .DO not think I need .CHEMOTHERAPY .BECAUSE I .SHOULD get comfort .CARE instead 0)
      3 (^me know.v (ans-to '(Do I need chemotherapy ?))) (0 :ulf)
    2 (^me know.v (ans-to '(Do I need chemotherapy ?))) (0 :ulf)
  1 (0 you think we .SHOULD .TALK to my oncologist about .CHEMOTHERAPY 0)
    2 (^me know.v (ans-to '(Do I need chemotherapy ?))) (0 :ulf)
  1 (0 you 3 think I need comfort .CARE 0)
    2 (^me know.v (ans-to '(Should I get comfort care ?))) (0 :ulf)
  1 (0 I .SHOULD .TAKE stronger .PAIN medication 0)
    2 (^me know.v (ans-to '(Can I have a stronger pain medication ?))) (0 :ulf)
  1 (0 I .SHOULD .TAKE something different 0)
    2 (^me know.v (ans-to '(Can I have a stronger pain medication ?))) (0 :ulf)
  1 (0 I .SHOULD wait to see if the .PAIN medication works 0)
    2 (^me know.v (ans-to '(Can I have a stronger pain medication ?))) (0 :ulf)
  1 (0 I 2 .GIVE you a refill of .PAIN medication 0)
    2 (^me know.v (ans-to '(I would like a refill of medicine \.))) (0 :ulf)
  1 (0 I 2 .GIVE you stronger .PAIN medication 0)
    2 (^me know.v (ans-to '(Can I have a stronger pain medication ?))) (0 :ulf)
  1 (0 the prognosis is that 0)
    2 (- 0 cancer 1 .BE treated 0)
      3 (- 0 may live 1 .NUMBER-VAGUE .ELAPSED-TIME 0)
        4 (- 0 cannot 1 .CURE 0)
          5 (- 0 hard 1 .PREDICT 0)
            6 (- 0 .NEG 2 .HAVE 1 .LONG 0)
              7 (^me know.v (ans-to '(What is my prognosis ?))) (0 :ulf)
  1 (0 I 1 sleeping poorly .BECAUSE 0)
    2 (^me know.v (ans-to '(Why have I not been sleeping well ?))) (0 :ulf)
  1 (0 the test results show that 0)
    2 (- 0 radiation 2 .NEG working 0)
      3 (- 0 I .HAVE cancer 0)
        4 (^me know.v (ans-to '(What do my test results mean ?))) (0 :ulf)
  1 (0 is a .TREATMENT .OPTION 0)
    2 (^me know.v (ans-to '(What are my options for treatment ?))) (0 :ulf)
  1 (0 a stronger .PAIN medication 3 .HELP me .SLEEP 0)
    2 (^me know.v (ans-to '(Will stronger pain medication help me sleep ?))) (0 :ulf)
  1 (0 my understanding of my prognosis 0)
    2 (^me know.v (ans-to '(Can I trust your prognosis ?))) (0 :ulf)
  1 (0 the majority of people 2 .HAVE an accurate prognosis 0)
    2 (^me know.v (ans-to '(Can I trust your prognosis ?))) (0 :ulf)
  1 (0 I .SHOULD .TELL my .FAMILY the full truth about the prognosis 0)
    2 (^me know.v (ans-to '(What should I tell my family ?))) (0 :ulf)
  1 (0 I .SHOULD .REASSURE my .FAMILY about the prognosis \.)
    2 (^me know.v (ans-to '(What should I tell my family ?))) (0 :ulf)
))