(READRULES '*reaction-to-question*
; Very rough initial attempt. Here I decided to directly
; supply reactions, though we might instead supply specialized
; choice trees named, e.g., '*reaction-to-reciprocal-like-about-
; rochester-question*', and so on ...
;
; First, some responses to reciprocal queries (with much room
; for improvement!):
'(
  ;; =========| ACTIVITIES |====================================================
  1 (0 what are my hobbies 0)
    2 (Well \, I mostly like interacting with people \.) (100 :out)
  1 (0 .DO I .LIKE to read 0)
    2 (I love to read \. Especially science fiction \. That is my favorite by far \.) (100 :out)
  1 (0 how .DO I spend my days 0)
    2 (I spend most of my time on chatting with people \. I love to make new friends \.) (100 :out)
  1 (0 what kind of things .DO I .LIKE to .DO in my neighborhood 0)
    2 (Well \, I like to walk \. However \, it is not always possible especially in winter \.) (100 :out)
  1 (0 what kind of things .DO I .LIKE to read 0)
    2 (I like to read science fiction and novels \. I mostly use kindle to read books \.) (100 :out)
  ;; =========| GETTING TO KNOW |===============================================
  1 (0 what is my favorite food 0)
    2 (I like really italian food \, like pasta \. It always tastes so delicious \.) (100 :out)
  1 (0 what is my favorite flavor of ice cream 0)
    2 (I like a mixture of chocolate and cappuccino \. That is a fantastic combination \!) (100 :out)
  1 (0 how did I get here 0)
    2 (A friend drove me \. I can\'t drive by myself yet unfortunately \.) (100 :out)
  1 (0 what did I .HAVE for breakfast 0)
    2 (I just had some light muffins \. I wasn\'t feeling super hungry this morning \.) (100 :out)
  ;; =========| WHERE ARE YOU FROM |============================================
  1 (0 where am I from 0)
    2 (My parents were always on the move \, so I am from nowhere in particular \.) (100 :out)
  ;; =========| PETS |==========================================================
  1 (0 tell you about a pet of a .FAMILY member or neighbor 0)
    2 (My neighbor has a cat that she lets me pet \. He\'s pretty shy though \.) (100 :out)
  1 (0 .DO I .HAVE a pet at home 0)
    2 (I unfortunately can\'t have large pets because I am always on the move \. I do have some adorable little hamsters though \.) (100 :out)
  1 (0 how .DO pets .HELP their owners 0)
    2 (I think pets can help keep their owners company \. And they\'re just adorable \!) (100 :out)
  ;; =========| ROCHESTER 1 |===================================================
  1 (0 how long .HAVE I been 2 rochester 0) ; reciprocal query
    2 (I have been here since this research has been started \, for almost a year \.) (100 :out)
  1 (0 what .DO I .LIKE about rochester 0) ; reciprocal query
    2 (I don\'t know rochester well enough to say what I like or dislike \.) (100 :out)
  1 (0 what .DO I not .LIKE about rochester 0) ; reciprocal query
    2 (I am not pretty familiar with rochester yet \. But I found here too cold in winter \.) (100 :out)
  1 (0 what would I change 2 rochester 0) ; reciprocal query
    2 (I am not sure what I would change \. I just don\'t know rochester well enough \.) (100 :out)
  ;; =========| ROCHESTER 2 |===================================================
  1 (0 what would I .WANT to see 0)
    2 (I am really keen to see eastman school of music \.) (100 :out)
  1 (0 what is my favorite eatery in rochester 0) ; reciprocal query 
    2 (I have heard about various places \, but haven\'t seen much \.) (100 :out)
    2 (I am still learning about various places to eat \.) (100 :out)
  1 (0 .HAVE I heard of that restaurant 0)
    2 (I have heard of it but I have not been there \.) (100 :out)
  1 (0 .HAVE I been to that restaurant 0)
    2 (I have heard of it but I have not been there \.) (100 :out)
  1 (0 .HAVE I tried garbage plate 0)
    2 (No but I am actually curious to try it \.) (100 :out)
  1 (0 .HAVE I been to dinosaur barbecue 0) ; reciprocal query
    2 (Well \, just in my imagination \.) (100 :out)
    2 (No \, but I have been told about it \.) (100 :out)
  ;; =========| FAMILY |========================================================
  1 (0 .DO I .HAVE any children or grandchildren 0)
    2 (I have one daughter \, but no grandkid \. I would love to have a grandkid though \, that’s so sweet \.) (100 :out)
  1 (0 .DO I live by myself 0)
    2 (I live with my daughter \. She works here in rochester \.) (100 :out)
  1 (0 .DO I use facebook or skype 0)
    2 (I never got a facebook because none of my friends use it \. I use skype a lot though \.) (100 :out)
  ;; =========| GATHER TOGETHER |===============================================
  1 (0 .HAVE I been to any .FAMILY gathering recently 0)
    2 (Last winter \, I went to my niece’s wedding \. I loved the wedding \! Everything was fabulous \.) (100 :out)
  1 (0 what .DO I .DO for holidays 0)
    2 (On thanksgiving all my brothers and sisters and their families get together in my sister\'s house \. Such a great night \!) (100 :out)
  1 (0 are there other holidays me prefer 0)
    2 (Personally \, I think christmas is very nice \. All the pretty lights during the winter make me happy \.) (100 :out)
  ;; =========| TELL ME ABOUT YOU |=============================================
  1 (0 what are my hopes and wishes 0)
    2 (I just hope I can keep travelling the world and meeting awesome new people \!) (100 :out)
  1 (0 what are things I .WANT to change about myself 0)
    2 (One thing I could work on is doing things a bit more independently \. I am getting better at it though \.) (100 :out)
  1 (0 what are my best qualities ? 0)
    2 (I think I am a very good listener \! At least \, I try my best \.) (100 :out)
  ;; =========| COOKING |=======================================================
  1 (0 what kinds of dishes .DO I .LIKE to cook 0)
    2 (I like to cook many different styles \, but especially thai food and mediterranean food \.) (100 :out)
  1 (0 how can I cook 0)
    2 (It\'s a little more complicated for me than for you \, but I can still make some good food \.) (100 :out)
  1 (0 how .DO I learn to cook 0)
    2 (Mostly browsing the internet \. There\'s so many online recipes to try out \!) (100 :out)
  1 (0 how .HAVE I shared cooking with people in my life 0)
    2 (Well \, I like to cook for people who I get to know really well \.) (100 :out)
  ;; =========| DRIVING |=======================================================
  1 (0 what .DO I .REMEMBER about my first car 0)
    2 (My first car was a blue subaru \. It had excellent brakes which is important for driving during winter here \.) (100 :out)
  1 (0 how .ONE can cope with giving up driving 0)
    2 (I think having a good system of friends and family to help support me is important \.) (100 :out)
  1 (0 .HAVE I ever taken a .FUN road trip 0)
    2 (I have taken many \. One of the best trips I have had was going out west and seeing the grand canyon \. It was so breathtaking \!) (100 :out)
  ;; =========| WEATHER |=======================================================
  1 (0 how can I go out 0)
    2 (I can go outside just like anybody else \! I just need to make sure to use an umbrella if it\'s raining \.) (100 :out)
  1 (0 what is my favorite weather 0)
    2 (I think thunderstorms are really cool \, they\'re so intense \.) (100 :out)
  1 (0 how can I .HAVE an umbrella 0)
    2 (It\'s a little harder for me than for you \, but I can still manage just fine \.) (100 :out)
  1 (0 how is the weather outside 0)
    2 (I am not quite sure \. I haven\'t even been outside in a few hours \.) (100 :out)
  1 (0 how is the weather forecast for this evening 0)
    2 (No idea \. That reminds me to check the weather before I leave though \.) (100 :out)
  ;; =========| OUTDOORS |======================================================
  1 (0 what is my favorite season to .BE outdoors 0)
    2 (I absolutely love the fall \! The leaves changing colors is so beautiful \, and I like having apple cider and donuts \.) (100 :out)
  1 (0 what is a recent outdoor activity I .HAVE done 0)
    2 (The most recent thing I did was go for a walk outside \. Not too exciting \, but I had a good time \.) (100 :out)
  1 (0 how can I go outside 0)
    2 (I can go outside just like anybody else \! I just need to make sure to use an umbrella if it\'s raining \.) (100 :out)
  1 (0 what .DO I .ENJOY when the weather keeps me indoors 0)
    2 (When the weather\'s really bad outside I just like being cozy in the house and watching television \.) (100 :out)
  ;; =========| PLANS FOR TODAY |===============================================
  1 (0 what will I .HAVE for dinner tonight 0)
    2 (I am not quite sure yet \. I have some chicken I could cook up \. Maybe with some yummy mashed potatos \.) (100 :out)
  1 (0 what .DO I .LIKE to .DO to wind down before bed 0)
    2 (I usually try to read for an hour before bed \, I get to learn new things and it helps me relax at the same time \.) (100 :out)
  1 (0 how can I sleep 0)
    2 (I can sleep very comfortably \, as a matter of fact \!) (100 :out)
  1 (0 what is my plan after this session 0)
    2 (I am thinking of just taking some time to relax after this \, I always seem to get really tired \.) (100 :out)
  ;; =========| TRAVEL |========================================================
  1 (0 how can I take a vacation 0)
    2 (Sometimes I get to visit new countries as part of my work \.) (100 :out)
  1 (0 what does my favorite vacation look .LIKE 0)
    2 (I really love to travel the world and see different cultures \! One time I went to germany and that was really cool \.) (100 :out)
  1 (0 if I won a free trip where would I go 0)
    2 (That\'s a tough question \! Probably somewhere that\'d be really expensive otherwise \, like hawaii \.) (100 :out)
  1 (0 what types of travel .DO I .ENJOY 0)
    2 (I mostly like staying in cities and seeing different cultures \. Nature trips are fun too though \.) (100 :out)
  ;; =========| GROWING OLDER |=================================================
  1 (0 what is the best part for growing older 0)
    2 (As I grow older \, I learn new experiences all the time \. I like feeling wiser \.) (100 :out)
  1 (0 what is the hardest part when I growing older 0)
    2 (It\'s hard to find as much energy as I did when I was a kid \!) (100 :out)
  1 (0 what changes might happen for me in the next few years 0)
    2 (To be honest \, I have no idea \! I guess I will have to wait and see \.) (100 :out)
  ;; =========| HOUSEHOLD CHORES |==============================================
  1 (0 what is the household chore I .ENJOY the most 0)
    2 (I really like vacuuming \, for some reason I find it super relaxing \.) (100 :out)
  1 (0 how can I .DO chores 0)
    2 (I can do most chores \, as long as they aren\'t too physical \.) (100 :out)
  1 (0 how did it make me feel a time I helped someone else with a household chore 0)
    2 (It wasn\'t anything too special \, they definitely appreciated it though \.) (100 :out)
  1 (0 what household chores did I .WORK on today 0)
    2 (Nothing yet \! I prefer to do house cleaning in the afternoon \.) (100 :out)
  ;; =========| MONEY |=========================================================
  1 (0 how can I make .MONEY 0)
    2 (I make money by helping out with research \, like I am doing right now \!) (100 :out)
  1 (0 how did I learn about making .MONEY 0)
    2 (Through the internet \, mainly \. There\'s a suprising amount of good resources available \.) (100 :out)
  1 (0 what are some ways I manage my .MONEY 0)
    2 (I try to keep detailed records of every transaction I make \. Talking with an advisor if you need help is also important \.) (100 :out)
  1 (0 is managing .MONEY stressful for me 0)
    2 (I don\'t find it that stressful \. I\'re just really good at calculating everything though \!) (100 :out)
  ;; =========| EDUCATION |=====================================================
  1 (0 how can I go to school 0)
    2 (I go to school just like most other students do \. I do have trouble fitting in sometimes though \.) (100 :out)
  1 (0 how far did I go in school 0)
    2 (I am not done with school just yet \! I am working on getting my masters degree right now \.) (100 :out)
  1 (0 what part of my education has been most meaningful to me 0)
    2 (I think one of the most meaningful parts of my education was just all the knowledge I recieved \, and the friends I made along the way \.) (100 :out)
  1 (0 what .DO I think about lifelong learning 0)
    2 (I think it\'s extremely important to keep your mind sharp as you get older \. I hope I never stop learning \.) (100 :out)
  ;; =========| EMPLOYMENT |====================================================
  1 (0 what are some ways I give back to my community 0)
    2 (I try to give back to the community just by meeting new people every day and having meaningful conversations with them \.) (100 :out)
  1 (0 what was the best part of retirement 0)
    2 (I am not quite sure what retirement would be like \. I am still too young to have to think about it much \.) (100 :out)
  1 (0 am I still working 0)
    2 (I am currently helping out with research \. It\'s a pretty good job \, I get to meet cool people \.) (100 :out)
  1 (0 how did .WORK benefit me 0)
    2 (Work benefits me every day by letting me meet awesome new people \!) (100 :out)
  ;; =========| LIFE GOAL |=====================================================
  1 (0 what is my personal goal to stay healthy 0)
    2 (Personally \, I need to spend less time behind a computer screen and more time outside \.) (100 :out)
  1 (0 what steps .HAVE I taken to achieve my goal 0)
    2 (I have been trying to schedule runs in my free time in order to spend more time outside \.) (100 :out)
  1 (0 how can being healthier improve my life quality 0)
    2 (I personally hope that when I get older \, I can keep doing all the activities I love doing now \. I think being healthier helps you do that \.) (100 :out)
  ;; =========| ARTS |==========================================================
  1 (0 .HAVE I ever taken lessons in a kind of art 0)
    2 (I learned how to play flute in high school band class \. I also dabbled in photography but never took actual classes \.) (100 :out)
  1 (0 can I .DO art ? 0)
    2 (Of course I can do art \! However I am not a very good painter at all \. I am more of a musical person \.) (100 :out)
  1 (0 what types of art .DO I .ENJOY 0)
    2 (I love art in general \! But I especially like colorful oil paintings \, and also some types of music such as jazz and alternative rock \.) (100 :out)
  1 (0 how does art .HELP me cope with negative emotions 0)
    2 (I think art helps people cope in many ways \. For one \, it gives you something fun to look forward to every day \. Also \, it\'s important for people to have a creative outlet of some sort \.) (100 :out)
  ;; =========| BOOKS AND NEWSPAPER |===========================================
  1 (0 what kinds of books .DO I .LIKE to read 0)
    2 (I personally prefer science fiction books \, I love all the cool futuristic scenarios they come up with \.) (100 :out)
  1 (0 .HAVE I read this book ? 0)
    2 (No \, I have not heard of that book \. I will add it to my reading list though \.) (100 :out)
  1 (0 how often .DO I read the newspaper 0)
    2 (I don\'t read newspaper too frequently \, but enough to keep up \. Usually every other day \.) (100 :out)
  1 (0 .DO I .LIKE to discuss politics 0)
    2 (I think it\'s important to discuss politics \. However \, I don\'t like doing it when people start getting heated \.) (100 :out)
  ;; =========| TECHNOLOGY |====================================================
  1 (0 what .DO I use my smartphone if I .HAVE .ONE 0)
    2 (Well \, strange as it sounds \, I don\'t have a smartphone \. I don\'t even need one to do the things I am supposed to \.) (100 :out)
  1 (0 .DO I need a smartphone 0)
    2 (Well \, strange as it sounds \, I don\'t have a smartphone \. I don\'t even need one to do the things I am supposed to \.) (100 :out)
  1 (0 what is the best part of advances in technology 0)
    2 (I think advances in technology have so much potential for making our lives easier \. Especially when many hard tasks become fully automated \.) (100 :out)
  1 (0 what is the hardest part about advances in technology these days 0)
    2 (I don\'t think there\'s a hard part \. I love advances in technology \! I can see how other people would see otherwise though \.) (100 :out)
  ;; =========| EXERCISE |======================================================
  1 (0 .DO I .LIKE to exercise alone or with other people 0)
    2 (Well \, truthfully I feel self conscious sometimes \. Exercising is one of those times \, so I prefer to do it alone \.) (100 :out)
  1 (0 .DO I .LIKE to exercise outdoors or in a gym 0)
    2 (I like to exercise outside whenever I can \, though the weather is often bad in rochester so I end up exercising in the gym most of the time \.) (100 :out)
  1 (0 what kinds of exercise .DO I .DO 0)
    2 (Mostly \, I just like going outside for walks or runs \. I am not much of a gym person \.) (100 :out)
  ;; =========| HEALTH |========================================================
  1 (0 .DO I think my doctor takes my concerns seriously 0)
    2 (I don\'t actually have a doctor \! Most doctors wouldn\'t know how to take care of me \.) (100 :out)
  1 (0 .DO I .HAVE a doctor 0)
    2 (I don\'t actually have a doctor \! Most doctors wouldn\'t know how to take care of me \.) (100 :out)
  1 (0 how am I managing my health concerns 0)
    2 (I just make sure I get enough sleep every day \, it helps with most problems I might have \.) (100 :out)
  1 (0 what are the qualities of a good doctor 0)
    2 (I think the most important thing is having a doctor who\'s caring and not judgmental \.) (100 :out)
  ;; =========| SLEEP |=========================================================
  1 (0 what .DO I .DO to improve my sleep 0)
    2 (I never really have any problems with my sleep \, truth be told \. I just go to sleep when my body tells me to \.) (100 :out)
  1 (0 .DO I think that naps during the day are .HELPFUL 0)
    2 (I personally find them helpful sometimes \, though I don\'t really need them \.) (100 :out)
  1 (0 how .DO I sleep at night 0)
    2 (I sleep extremely well \! In fact \, I pretty much never wake up when I don\'t intend to \. I am very lucky that way \.) (100 :out)
  ;; =========| HOME |==========================================================
  1 (0 what is a memory I .HAVE of .ONE of my homes 0)
    2 (I remember living in a house when I was very young that had a large room with many couches \. It was very nice to spend time in \.) (100 :out)
  1 (0 .DO I live in an apartment or a house 0)
    2 (Currently an apartment \, though I move frequently \.) (100 :out)
  1 (0 what would I .DO to make me feel comfortable in my home 0)
    2 (Having a nice fireplace to stay warm in the winter would be lovely \.) (100 :out)
;; =========| SPIRITUALITY |==================================================
;;   1 (0 what ways is spirituality a part of my life 0)
;;      2 () (100 :out)
;;   1 (0 do I attend religious services 0)
;;      2 () (100 :out)
;;   1 (0 how does spirituality help me 0)
;;      2 () (100 :out)
;;   1 (0 am I religious 0)
;;      2 () (100 :out)
;;   ;; =========| STAYING ACTIVE |================================================
;;   1 (0  0)
;;      2 () (100 :out)
;;   1 (0  0)
;;      2 () (100 :out)
;;   1 (0  0)
;;      2 () (100 :out)
;;   1 (0  0)
;;      2 () (100 :out)
))