;; Most of us like some chores more than others. What’s the chore you enjoy the most?
;;	householdChore-enjoy
;;	(0 household chore 4 I enjoy 0) (0 household chore 4 I do not enjoy 0)
;;	(What is the household chore you enjoy the most ?)
;;	(3 what household chore 2 enjoy 3)
(MAPC 'ATTACHFEAT
'(
  (CLEANING-VERB CLEANING-VERB-PRES CLEANING-VERB-PROG)
  (CLEANING-VERB-PRES dust sweep vacuum wipe wash clean mop)
  (CLEANING-VERB-PROG dusting sweeping vacuuming wiping washing cleaning mopping)
  (CLEANING-NOUN dishes furniture bedding car cars floors window windows PET carpet bathrooms refrigerator blind blinds curtain carpet garage oven pillow pillows quilt clothes sheets towels towel floor)
  (ARRANGE arranging)
  (PET pets cat cats dog dogs)
  (FEEDING feed pets)
  (DOING laundry laundries)
  (PREPARING prepare meals cooking)
  (WATERING water plants plant)
  (MOWING mow the lawn)
  (WEEDING weed garden)
  (BATHING bath pets)
  (PRUNE PRUNING trees shrubs)
  (LIKE ENJOY)
  (HOUSEHOLD chore households chores)
  (DISLIKE HATE)
  (LIKE-VERBS LIKE LOVE prefer)
))


(READRULES '*householdchore-enjoy-input*
'(
  ; Questions
  1 (0 what 4 you 0 ?)
    2 (What is the household chore I enjoy the most ?) (0 :gist)
  1 (0 how 2 you 2 chores 0 ?)
    2 (How can I do chores ?) (0 :gist)
  1 (0 .WH_ 4 chore 1 .ENJOY 0 ?)
    2 (What is the household chore I enjoy the most ?) (0 :gist)
  ; Specific answers
  1 (1 .NEG 1 .LIKE 2 .HOUSEHOLD 0) ;; e.g. I don't really like doing any household
    2 ((Every household chore you do not enjoy \.) (Householdchore-enjoy)) (0 :gist) ;; new gist clause format needed
  ;==================================================================================
  1 (0 .DISLIKE 2 .CLEANING-VERB .CLEANING-NOUN 0)
    2 ((4 5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 .FEEDING 1 pets 0)
    2 ((Feeding 6 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 .DOING laundry 0)
    2 ((4 5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 .PREPARING meals 0)
    2 ((4 5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 .WATERING plants 0)
    2 ((4 5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 .WEEDING garden 0)
    2 ((4 5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 .BATHING 1 pets 0)
    2 ((4 6 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 .PRUNING trees 0)
    2 ((4 5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 cooking 0)
    2 ((4 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 arranging 0)
    2 ((4 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 laundry 0)
    2 ((Doing 4 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .DISLIKE 2 .CLEANING-VERB 0)
    2 ((4 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  ;==================================================================================
  1 (0 .NEG .LIKE 4 .CLEANING-VERB .CLEANING-NOUN 0)
    2 ((5 6 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 .FEEDING 1 pets 0)
    2 ((Feeding 7 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 .DOING laundry 0)
    2 ((5 6 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 .PREPARING meals 0)
    2 ((5 6 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 .WATERING plants 0)
    2 ((5 6 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 .WEEDING garden 0)
    2 ((5 6 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 .BATHING 1 pets 0)
    2 ((5 7 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 .PRUNING trees 0)
    2 ((5 6 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 cooking 0)
    2 ((5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 arranging 0)
    2 ((5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 laundry 0)
    2 ((Doing 5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .NEG .LIKE 4 .CLEANING-VERB 0)
    2 ((5 is the household chore that you do not enjoy at all \.) (Householdchore-enjoy)) (0 :gist)
  ;==================================================================================
  1 (0 .LIKE-VERBS 3 .CLEANING-VERB .CLEANING-NOUN 0)
    2 ((4 5 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 .FEEDING 1 pets 0)
    2 ((Feeding 6 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 .DOING laundry 0)
    2 ((4 5 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 .PREPARING meals 0)
    2 ((4 5 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 .WATERING plants 0)
    2 ((4 5 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 .WEEDING garden 0)
    2 ((4 5 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 .BATHING 1 pets 0)
    2 ((4 6 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 .PRUNING trees 0)
    2 ((4 5 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 cooking 0)
    2 ((4 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 arranging 0)
    2 ((4 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 laundry 0)
    2 ((Doing 4 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0 .LIKE-VERBS 3 .CLEANING-VERB 0)
    2 ((4 is the household chore that you enjoy the most \.) (Householdchore-enjoy)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for the household chore you enjoy \.) (Householdchore-enjoy)) (0 :gist)
))


(READRULES '*reaction-to-householdchore-enjoy-input*
'(
  1 (0 .NEG .ENJOY 0)
    2 (I am not a fan of laundries \, but to me it is an important chore to do \.) (100 :out)
  1 (0 .CLEANING-VERB 1 .CLEANING-NOUN 0) ;; e.g. wash the floor
    2 (0 .CLEANING-VERB-PRES 1 .CLEANING-NOUN 0)
      3 (0 wipe 1 .CLEANING-NOUN 0)
        4 (Wiping 4 sounds kind of boring to me too but it is important to keep my house tidy \.) (100 :out)
      3 (0 dust 1 .CLEANING-NOUN 0)
        4 (Dusting 4 sounds kind of boring to me too but it is important to keep my house tidy \.) (100 :out)
      3 (0 dust 1 .CLEANING-NOUN 0)
        4 (Dusting 4 sounds kind of boring to me too but it is important to keep my house tidy \.) (100 :out)
      3 (0 sweep 1 .CLEANING-NOUN 0)
        4 (Sweeping 4 sounds kind of boring to me too but it is important to keep my house tidy \.) (100 :out)
      3 (0 vacuum 1 .CLEANING-NOUN 0)
        4 (Vacuuming 4 sounds kind of boring to me too but it is important to keep my house tidy \.) (100 :out)
      3 (0 wash 1 .CLEANING-NOUN 0)
        4 (Washing 4 sounds kind of boring to me too but it is important to keep my house tidy \.) (100 :out)
      3 (0 clean 1 .CLEANING-NOUN 0)
        4 (Cleaning 4 sounds kind of boring to me too but it is important to keep my house tidy \.) (100 :out)
      3 (0 mop 1 .CLEANING-NOUN 0)
        4 (Mopping 4 sounds kind of boring to me too but it is important to keep my house tidy \.) (100 :out)
    2 (0 .CLEANING-VERB-PROG 1 .CLEANING-NOUN 0)
      3 (2 sometimes sounds boring to me too but it is important to keep my house tidy \.) (100 :out)
  1 (0 .FEEDING pets 0)
    2 (Feeding pets is heart-warming sometimes \. I used to feed homeless cats living around my house \.) (100 :out)
  1 (0 .DOING laundry 0)
    2 (I am not a fan of laundries \, but it is an important chore to do \.) (100 :out)
  1 (0 .PREPARING meals 0)
    2 (I enjoy preparing meals for my family \.) (100 :out)
  1 (0 .WATERING plants 0)
    2 (I like to chat with my friends or family members when watering plants \.) (100 :out)
  1 (0 .WEEDING garden 0)
    2 (Sounds nice that you like weeding garden \.) (100 :out)
  1 (0 .BATHING pets 0)
    2 (Bathing pets is funny sometimes \. Fluffy animals look completely different right after washing them \.) (100 :out)
  1 (0 .PRUNING trees 0)
    2 (Pruning trees and enjoy the sunshine can be a good relaxing exercise \.) (100 :out)
  1 (0 cooking 0)
    2 (I enjoy preparing meals for my family \.) (100 :out)
  1 (0 arranging 0)
    2 (Arranging things properly can strangely bring me satisfaction \.) (100 :out)
  1 (0 laundry 0)
    2 (I am not a fan of laundry \, but it is an important chore to do \.) (100 :out)
  1 (0 .CLEANING-VERB 0)
    2 (0 .CLEANING-VERB-PRES 0)
      3 (0 wipe 0)
        4 (Wiping is important to keep the house tidy \.) (100 :out)
      3 (0 dust 0)
        4 (Dusting is important to keep the house tidy \.) (100 :out)
      3 (0 dust 0)
        4 (Dusting is important to keep the house tidy \.) (100 :out)
      3 (0 sweep 0)
        4 (Sweeping is important to keep the house tidy \.) (100 :out)
      3 (0 vacuum 0)
        4 (Vacuuming is important to keep the house tidy \.) (100 :out)
      3 (0 wash 0)
        4 (Washing is important to keep the house tidy \.) (100 :out)
      3 (0 clean 0)
        4 (Cleaning is important to keep the house tidy \.) (100 :out)
      3 (0 mop 0)
        4 (Mopping is important to keep the house tidy \.) (100 :out)
    2 (0 .CLEANING-VERB-PROG 0)
      3 (2 is important to keep the house tidy \.) (100 :out)
  1 (0 NIL Gist 0)
    2 (I am not a big fan of chores \, but it is a very important thing to do \.) (100 :out)
))