;; What will you have for dinner tonight?
;; (0 I will have 3 for dinner tonight 0)
;; dinner-tonight
;; (2 What you have 2 dinner tonight 2)
(MAPC 'ATTACHFEAT
'(
  (FOOD-DESCS sweet sour savory salty bitter dry crunchy spicy bbq bbq barbecue butters cheese cheeses)
  (BREAKFAST sandwich sandwiches panini pancake pancakes egg eggs omelette milk cheddar pudding)
  (AMERICAN-DISHES burgers burger cheeseburger cheeseburgers hamburger hamburgers pizza pizzas wings taco tacos)
  (FOOD-ETHNICITY asian chinese mexican japanese italian korean peruvian thai ethiopian indian mediterranean greek cambodian german polish spanish)
  (MEAT meats pork CHICKEN lamb lobster ribs rib pepperoni ham salami bacon meatball meatballs sausage sausages)
  (CHICKEN turkey)
  (STEAKS steak beefs beef)
  (SEAFOOD salmon salmons tuna bass lobster lobsters shrimp shrimps crab crabs fish fishes shellfish shellfishes cod eel herring sardines swordfish tilapia trout caviar oyster clam clams squid octopus calamari)
  (VEGETABLE VEGETABLE-SINGL VEGETABLE-PLUR)
  (VEGETABLE-SINGL salad tomato mushroom mushrooms onion onions spinich lettuce asparagus broccoli carrot vegan vegetarian avocado eggplant pepper quinoa soy pickle corn pea leek pumpkin beet kale zucchini cabbage celery garlic cauliflower cucumber)
  (VEGETABLE-PLUR salads tomatos mushrooms onions broccolis carrots peppers pickles peas beets kales cabbages)
  (JAPANESE-FOOD sushi seawead ramen sashimi tempora matcha)
  (MEXICAN-FOOD burrito burritos)
  (SOUP soups chowder succotash)
  (TANGERINE cantaloupe honeydew olive olives plantains)
  (FOOD-DESSERT cookie cookies brownies candy pie cheesecake chocolate custard pastry pastries ice cream doughnut donut doughnuts donuts shortcake sundae cake yogart)
  (FOOD-GRAIN pasta spaghetti rice noodles oats oatmeal bread toast cereal bran pancake pancakes waffle waffles fries sub subs bagel bagels curry)
  (FOOD-WAY-OF-COOKING boiled smoked baked steamed grilled strip french stew buffalo sweet salty spicy sirloin stuffing curry curried chili)
  (FOOD-TWO apple pie pies hot dog dogs sweet mashed potato potatos)
  (ROCHESTER-RESTAURANT nick tahoe\'s tahou\'s garbage plate dinosaur barbecue aladdin\'s chipotle pane vino tapas pita lounge tavern vine lento luck gate max owl golden port dim sum galleria rocco laluna he\'s salena\'s tournedos tornadoes tony d\'s edibles espada espada hot rosita\'s rocky\'s pellegrino\'s scotland yard char christopher\'s veneto john\'s tex-mex matthew\'s east end magnolia\'s bacco\'s hogan\'s hideaway roncone\'s panzari\'s jines nays el savor de la isla el taino chen\'s GARDEN monte alban elmwood inn sinbad\'s stromboli\'s greens legends dogtown sticky lips distillery tropics stock exchange spiro\'s villa bill gray\'s trata el latino mitch\'s mitches village phillips phillip\'s philip\'s chophouse bazil basil delmonico\'s taste ethiopia mex wang\'s fiamma fong ristorante lucano papa joe\'s bee peppa pot havana cuba keenan\'s rizzi\'s grinnell\'s latino antonetta\'s king foo choice remington\'s rick\'s prime rib eros nikko lao charlie brown\'s meda zeppa osteria trinities yangtze romeo\'s henry b\'s cafe cibon carmine\'s red front peppermill nathaniel\'s win sal\'s birdland ridge pomodoro olympia valicia\'s diner hose mcginnity\'s mr \. dominic\'s shui pelican\'s nest cj\'s southern soul campi\'s campies jim\'s mcdonald\'s king hut wendy\'s chipotle pit danforth douglass douglas mel panda express tim horton\'s dibella\'s cam\'s bunga burger saha india grappaf pura vida blimpie starbucks subway brooks landing boulder holley\'s holly\'s hollies steve t\'s jay\'s)
))


(READRULES '*dinner-tonight-input*
'(
  ; Questions
  1 (0 what 2 you 0 ?)
    2 (What will I have for dinner tonight ?) (0 :gist)
  1 (0 how 2 you .COOK 0 ?)
    2 (How can I cook ?) (0 :gist)
  1 (0 .WH_ 4 .DINNER 0 ?)
    2 (What will I have for dinner tonight ?) (0 :gist)
  ; Specific answers
  1 (0 .FOOD-ETHNICITY 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .FOOD-WAY-OF-COOKING 1 .MEAT 0)
    2 ((You will have 2 4 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .FOOD-WAY-OF-COOKING 1 .SEAFOOD 0)
    2 ((You will have 2 4 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .MEAT 1 grain 0)
    2 ((You will have 2 4 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .SEAFOOD 1 grain 0)
    2 ((You will have 2 and 4 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .MEAT 1 .SOUP 0)
    2 ((You will have 2 4 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .SEAFOOD 1 .SOUP 0)
    2 ((You will have 2 4 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .VEGETABLE 1 .SOUP 0)
    2 ((You will have 2 4 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .FOOD-TWO .FOOD-TWO 0)
    2 ((You will have 2 3 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .MEAT 3 .VEGETABLE 0)
    2 ((You will have 2 and 4 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .AMERICAN-DISHES 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .MEAT 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .SEAFOOD 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .FOOD-DESCS 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .JAPANESE-FOOD 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .FOOD-GRAIN 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .SOUP 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 dessert 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .VEGETABLE 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0 .MEXICAN-FOOD 0)
    2 ((You will have 2 for dinner tonight \.) (Dinner-tonight)) (0 :gist)
  1 (0)
    2 ((NIL Gist \: nothing found for what you will have for dinner tonight \.) (Dinner-tonight)) (0 :gist)
))


(READRULES '*reaction-to-dinner-tonight-input*
'(
  1 (0 .FOOD-ETHNICITY 0)
    2 (0 japanese 0)
      3 (I like japanese dessert \! I still eat some though I cannot eat too much \.) (100 :out)
    2 (0 italian 0)
      3 (Italian pizza can be really delicious \.) (100 :out)
    2 (0 chinese 0)
      3 (Nice that you are going to eat chinese food \! I am a big fan of sushi \.) (100 :out)
    2 (0 asian 0)
      3 (Asian food seem to be popular in rochester \. They have many asian or asian fusion restaurant \.) (100 :out)
    2 (0 .FOOD-ETHNICITY 0)
      3 (I don\'t usually eat 2 food \. I do like to try them though \.) (100 :out)
  1 (0 .FOOD-WAY-OF-COOKING 1 .MEAT 0)
    2 (0 .CHICKEN 0)
      3 (I start to like eating 2 recently since it is relatively healthier \.) (100 :out)
    2 (0 beef 0)
      3 (Medium 2 is the best \. I love eating it \.) (100 :out)
    2 (0 .MEAT 0)
      3 (My husband loved 2 \. I used to cook regularly for him \.) (100 :out)
  1 (0 .FOOD-WAY-OF-COOKING 1 .SEAFOOD 0)
    2 (I love eating 4 since seafood is good for your heath and taste delicious \.) (100 :out)
  1 (0 .MEAT 1 grain 0)
    2 (0 .CHICKEN 0)
      3 (I start to like eating 2 recently since it is relatively healthier \.) (100 :out)
    2 (0 beef 0)
      3 (Medium 2 is the best \. I love eating it \.) (100 :out)
    2 (0 .MEAT 1 grain 0)
      3 (I eat 2 with 4 \. They taste great \.) (100 :out)
  1 (0 .SEAFOOD 1 grain 0)
    2 (0 salmon 0)
      3 (Salmon is great \! I love eating it \.) (100 :out)
    2 (0 shrimp 0)
      3 (Shrimp tastes good \. I cooked shrimp spaghetti and I absolutely loved it \.) (100 :out)
    2 (0 .SEAFOOD 1 grain 0)
      3 (Seafood is really good for my heath \. I am happy to hear that you are planning to eat 2 \.) (100 :out)
  1 (0 .MEAT .SOUP 0)
    2 (I love soup \! They are easy to make and tasty \.) (100 :out)
  1 (0 .SEAFOOD .SOUP 0)
    2 (Soup made of 2 sounds truely delicious \!) (100 :out)
  1 (0 .VEGETABLE 1 .SOUP 0)
    2 (I love to have some soup as the appetizer \.) (100 :out)
  1 (0 .FOOD-TWO .FOOD-TWO 0)
    2 (My grandchildren love to eat 2 4 \.) (100 :out)
  1 (0 .MEAT 3 .VEGETABLE 0)
    2 (It is healthy to eat meats with vegetables like 4 \.) (100 :out)
  1 (0 .AMERICAN-DISHES 0)
    2 (Young people today love to hang out and eat 2 \. I love 2 too \!) (100 :out)
  1 (0 .MEAT 0)
    2 (0 .CHICKEN 0)
      3 (I start to like eating 2 recently since it is relatively healthier \.) (100 :out)
    2 (0 beef 0)
      3 (Medium 2 is the best \. I love eating it \.) (100 :out)
    2 (0 .MEAT 1 grain 0)
      3 (I eat 2 from time to time \. They taste great \.) (100 :out)
  1 (0 .SEAFOOD 0)
    2 (I feel wonderful eating 2 \. Wish I will have a great dinner \!) (100 :out)
  1 (0 .FOOD-DESCS 0)
    2 (0 sweet 0)
      3 (I love eating sweet and salty food \. Hope you will have a great dinner \.) (100 :out)
    2 (0 salty 0)
      3 (I love eating sweet and salty food \. Hope you will have a great dinner \.) (100 :out)
    2 (0 .FOOD-DESCS 0)
      3 (2 food can taste great sometime \. Hope you will have a great dinner \.) (100 :out)
  1 (0 .JAPANESE-FOOD 0)
    2 (I love japanese food \. I am planning to go to shiki \, a japanese restaurant here tomorrow for dinner \.) (100 :out)
  1 (0 .FOOD-GRAIN 0)
    2 (2 sounds like a nice thing to eat \.) (100 :out)
  1 (0 .SOUP 0)
    2 (2 must be delicious \! I am happy to hear that \.) (100 :out)
  1 (0 dessert 0)
    2 (I would love to eat desserts like ice cream after a meal \.) (100 :out)
  1 (0 .VEGETABLE 0)
    2 (0 .VEGETABLE-SINGL 0)
      3 (2 is healthy to eat \. I wish you will enjoy your meal \!) (100 :out)
    2 (0 .VEGETABLE-PLUR 0)
      3 (2 are healthy to eat \. I wish you will enjoy your meal \!) (100 :out)
  1 (0 .MEXICAN-FOOD 0)
    2 (Burritos are nice for dinner \. Wish you will enjoy your dinner \!) (100 :out)
  1 (0 NIL Gist 0)
    2 (I hope your dinner tonight is tasty \.) (100 :out)
))